# See https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx#values for configuration reference
controller:
  proxySetHeaders:
    X-Original-Host: "$host"
  progressDeadlineSeconds: null # Workaround: Please see https://github.com/helm/helm/issues/30878
