apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: {{ .Values.name }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  controllerNamePrefix: {{ .Values.name }}
  defaultSSLCertificate:
    forceSSLRedirect: false
    secret:
      name: star-azure-defra-cloud-cert
      namespace: defra-certs
  {{- with .Values.loadBalancerAnnotations }}
  loadBalancerAnnotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  customHTTPErrors:
    - 502
    - 503
    - 504

  defaultBackendService:
    name: error-page
    namespace: app-routing-system



