apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .Values.applicationName }}
  labels:
    kubernetes.io/service-name: {{ .Values.applicationName }}
endpoints:
  - addresses:
      - 192.168.5.2 # IP address of the host from with in the lima vm
addressType: IPv4
ports:
  - port: {{ .Values.local.port }}