apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: {{ .Release.Name }}
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Release.Name }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
            path: /
            pathType: Prefix