parameters:
  name: nodeVersion
  type: string

jobs:
  - job: BuildNodeProject
    displayName: Build Node Project
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ${{ parameters.nodeVersion }}
          addToPath: true
        displayName: Install Node and NPM and add to path

      - script: |
          npm --prefix ./service ci
          npm --prefix ./service run build
        displayName: Install dependencies and build

# vim: set ts=2 sts=2 sw=2 et:
