parameters:
  - name: mvnGoals
    type: string
    default: verify jacoco:report package
  - name: mavenPomFile
    type: string
    default: 'service/pom.xml'
  - name: mavenSettingsFile
    type: string
    default: 'service/pom.xml'
  - name: jacocoFile
    type: string
    default: $(System.DefaultWorkingDirectory)/service/target/site/jacoco/jacoco.xml
  - name: srcPaths
    type: string
    default: $(System.DefaultWorkingDirectory)/service/src/main/java/
  - name: targetPath
    type: string
    default: $(Build.SourcesDirectory)/service/target

jobs:
  - job: BuildJavaProject
    displayName: Build Java Project
    condition: and(not(failed()), not(canceled()), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
      MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
    steps:
      - task: DownloadSecureFile@1
        name: mavenSettings
        displayName: 'Download Maven Settings'
        inputs:
          secureFile: 'maven-settings.xml'

      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo

      - task: Maven@4
        displayName: 'Build and Test'
        inputs:
          mavenPomFile: ${{ parameters.mavenPomFile }}
          mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.21'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          options: '--settings $(mavenSettings.secureFilePath)'
          goals: ${{ parameters.mvnGoals }}

      - task: PublishCodeCoverageResults@2
        displayName: 'Publish code coverage'
        inputs:
          summaryFileLocation: ${{ parameters.jacocoFile }}
          pathToSources: ${{ parameters.srcPaths }}

      - task: PublishPipelineArtifact@1
        displayName: Publish service artifact
        inputs:
          artifact: service
          targetPath: ${{ parameters.targetPath }}

