parameters:
  name: nodeVersion
  type: string

jobs:
  - job: BuildNodeProject
    displayName: Build Node Project
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ${{ parameters.nodeVersion }}
          addToPath: true
        displayName: Install Node and NPM and add to path

      - script: |
          npm --prefix ./service ci
          npm --prefix ./service run build
        displayName: 'Install dependencies and build'

      - task: CopyFiles@2
        displayName: 'Copy public'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/service/public'
          Contents: '**'
          TargetFolder: '$(Build.SourcesDirectory)/service_artifact/public'

      - task: PublishPipelineArtifact@1
        inputs:
          artifact: 'service'
          targetPath: '$(Build.SourcesDirectory)/service_artifact'
        displayName: Install dependencies and build

# vim: set ts=2 sts=2 sw=2 et:
