parameters:
  - name: environmentName
    type: string
    values:
      - POC
  - name: migrationsClientId
    type: string
  - name: namespace
    type: string
  - name: serviceClientId
    type: string
  - name: servicePrincipalName
    type: string
  - name: repository
    type: string
  - name: serviceName
    type: string
  - name: serviceVersion
    type: string

jobs:
  - job: DeployChart
    displayName: Deploy Helm Charts
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"

    steps:
      - checkout: ${{ parameters.repository }}

      - task: AzureCLI@2
        name: LoginToContainerRegistry
        displayName: Login to Azure Container Registry
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az acr login --name $(acrName)

      - task: Kubernetes@1
        name: KubectlLogin
        displayName: Configure Kubernetes client and authenticate
        inputs:
          connectionType: Azure Resource Manager
          azureSubscriptionEndpoint: $(serviceConnection)
          azureResourceGroup: $(resourceGroupName)
          kubernetesCluster: $(kubernetesCluster)
          useClusterAdmin: true
          command: login

      - task: AzureCLI@2
        name: DeployHelmCharts
        displayName: Deploy Helm Charts
        env:
          ENVIRONMENT: ${{ lower(parameters.environmentName) }}
          AZURE_LOCATION: $(location)
          AZURE_CONTAINER_REGISTRY_HOST: $(acrLoginServer)
          AZURE_TENANT_ID: $(tenantId)
          AZURE_MANAGED_IDENTITY_CLIENT_ID: ${{ parameters.serviceClientId }}
          AZURE_MANAGED_IDENTITY_PRINCIPAL_NAME: ${{ parameters.servicePrincipalName }}
          AZURE_MANAGED_IDENTITY_MIGRATIONS_CLIENT_ID: ${{ parameters.migrationsClientId }}
          AZURE_MANAGED_IDENTITY_EXTERNAL_SECRETS_CLIENT_ID: $(externalSecretsClientId)
          CONTAINER_IMAGE: "ipaffs/${{ parameters.serviceName }}:${{ parameters.serviceVersion }}"
          MIGRATIONS_IMAGE: "ipaffs/{{ parameters.serviceName }})-configuration:${{ parameters.serviceVersion }}"
          NAMESPACE: ${{ parameters.namespace }}
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            curl -L https://github.com/helmfile/helmfile/releases/download/v1.1.9/helmfile_1.1.9_linux_amd64.tar.gz | tar -xz && \
            chmod +x ./helmfile && \
            ./helmfile init --force && \
            ./helmfile apply --debug

## vim: set ts=2 sts=2 sw=2 et:
