parameters:
  - name: environmentName
    type: string
    default: DEV

  - name: migrations
    type: boolean
    default: false

  - name: namespace
    type: string

  - name: serviceName
    type: string

jobs:
  - job: MigrationsIdentity
    displayName: Set up Migrations Identity
    condition: and(not(failed()), not(canceled()), ${{ eq(parameters.migrations, true) }})
    variables:
      - group: Common
      - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
        - group: HigherEnvs
      - ${{ else }}:
        - group: LowerEnvs
      - group: "${{ parameters.environmentName }}"
      - template: "vars/common.yaml"
      - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
      - name: lowerResourceGroupName
        value: $[lower(variables.resourceGroupName)]

    steps:
      - checkout: ipaffs-infra

      - task: AzureCLI@2
        name: CreateIdentity
        displayName: Create Managed Identity and Federated Credential
        env:
          MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-${{ parameters.namespace }}-${{ parameters.serviceName }}-migrations
          RESOURCE_GROUP_NAME: $(resourceGroupName)
          AKS_CREDENTIAL: ${{ parameters.serviceName }}-migration
          AKS_ISSUER: $(aksOidcIssuer)
          AKS_AUDIENCES: "api://AzureADTokenExchange"
          AKS_SUBJECT: "system:serviceaccount:${{ parameters.namespace }}:${{ parameters.serviceName }}-migrations"
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/create-identity.sh

      - task: AzureCLI@2
        name: AddToSearchContributorsGroup
        displayName: Add Managed Identity to Search Contributors Group
        env:
          GROUP_ID: $(searchContributorsGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/add-principal-to-group.sh

      - task: AzureCLI@2
        name: AddToBlobStorageContributorsGroup
        displayName: Add Managed Identity to Blob Storage Contributors Group
        env:
          GROUP_ID: $(blobStorageContributorsGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/add-principal-to-group.sh

      - task: AzureCLI@2
        name: AddToSQLAdminsGroup
        displayName: Add Managed Identity to SQL Admin Group
        env:
          GROUP_ID: $(sqlAdminGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/add-principal-to-group.sh

      - task: AzureCLI@2
        name: WaitForGroupMembership
        displayName: Wait for group membership
        env:
          GROUP_ID: $(sqlAdminGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/wait-for-group-membership.sh

      - task: AzureCLI@2
        name: EnsureAsoManagedIdentity
        displayName: Ensure ASO Managed Identity Resource
        env:
          AKS_NAME: $(kubernetesCluster)
          AKS_RESOURCE_GROUP_NAME: $(resourceGroupName)
          AKS_SUBSCRIPTION_NAME: $(subscriptionName)
          LOCATION: $(location)
          MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-${{ parameters.namespace }}-${{ parameters.serviceName }}-migrations
          NAMESPACE: ${{ parameters.namespace }}
          OWNER_RESOURCE_GROUP_NAME: $(lowerResourceGroupName)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/ensure-aso-managed-identity.sh

  - job: ServiceIdentity
    displayName: Set up Service Identity
    variables:
      - group: Common
      - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
        - group: HigherEnvs
      - ${{ else }}:
        - group: LowerEnvs
      - group: "${{ parameters.environmentName }}"
      - template: "vars/common.yaml"
      - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
      - name: lowerResourceGroupName
        value: $[lower(variables.resourceGroupName)]

    steps:
      - checkout: ipaffs-infra

      - task: AzureCLI@2
        name: CreateIdentity
        displayName: Create Managed Identity and Federated Credential
        env:
          MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-${{ parameters.namespace }}-${{ parameters.serviceName }}-service
          RESOURCE_GROUP_NAME: $(resourceGroupName)
          AKS_CREDENTIAL: ${{ parameters.serviceName }}-service
          AKS_ISSUER: $(aksOidcIssuer)
          AKS_AUDIENCES: "api://AzureADTokenExchange"
          AKS_SUBJECT: "system:serviceaccount:${{ parameters.namespace }}:${{ parameters.serviceName }}-service"
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/create-identity.sh

      - task: AzureCLI@2
        name: AddToSearchContributorsGroup
        displayName: Add Managed Identity to Search Contributors Group
        env:
          GROUP_ID: $(searchContributorsGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/add-principal-to-group.sh

      - task: AzureCLI@2
        name: AddToBlobStorageContributorsGroup
        displayName: Add Managed Identity to Blob Storage Contributors Group
        env:
          GROUP_ID: $(blobStorageContributorsGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/add-principal-to-group.sh

      - task: AzureCLI@2
        name: WaitForGroupMembership
        displayName: Wait for group membership
        env:
          GROUP_ID: $(searchContributorsGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/wait-for-group-membership.sh

      - task: AzureCLI@2
        name: AddToSQLAdminsGroup
        displayName: Add Managed Identity to SQL Admin Group
        env:
          GROUP_ID: $(sqlAdminGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/add-principal-to-group.sh

      - task: AzureCLI@2
        name: WaitForGroupMembership
        displayName: Wait for group membership
        env:
          GROUP_ID: $(sqlAdminGroupId)
          PRINCIPAL_ID: $(principalId)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/wait-for-group-membership.sh

      - task: AzureCLI@2
        name: EnsureAsoManagedIdentity
        displayName: Ensure ASO Managed Identity Resource
        env:
          AKS_NAME: $(kubernetesCluster)
          AKS_RESOURCE_GROUP_NAME: $(resourceGroupName)
          AKS_SUBSCRIPTION_NAME: $(subscriptionName)
          LOCATION: $(location)
          MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-${{ parameters.namespace }}-${{ parameters.serviceName }}-service
          NAMESPACE: ${{ parameters.namespace }}
          OWNER_RESOURCE_GROUP_NAME: $(lowerResourceGroupName)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptPath: scripts/pipeline/ensure-aso-managed-identity.sh

# vim: set ts=2 sts=2 sw=2 et:
