parameters:
  - name: environmentName
    type: string

  - name: serviceConnection
    type: string
    default: ""

  - name: migrationsClientId
    type: string
    default: ""

  - name: namespace
    type: string

  - name: namespaceResourceGroupName
    type: string
    default: ""

  - name: serviceClientId
    type: string
    default: ""

  - name: servicePrincipalName
    type: string
    default: ""

  - name: serviceName
    type: string

  - name: serviceVersion
    type: string

  - name: repository
    type: string
    default: self

  - name: helmfileAction
    type: string
    default: apply

  - name: helmfileDebug
    type: boolean
    default: false

  - name: helmfileSelector
    type: string
    default: ""

  - name: adoEnvironment
    type: string
    default: ""

  - name: postSteps
    type: stepList
    default: []

  - name: acrNameOverride
    type: string
    default: ""

  - name: acrLoginServerOverride
    type: string
    default: ""

jobs:
  - ${{ if eq(parameters.adoEnvironment, '') }}:
      job: DeployChart
    ${{ else }}:
      deployment: DeployChart
      environment:
        name: ${{ parameters.adoEnvironment }}
    displayName: Deploy Helm Charts
    variables:
      - group: Common
      - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
        - group: HigherEnvs
      - ${{ else }}:
        - group: LowerEnvs
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
      - name: HELMFILE_TOOLCHAIN_DIRECTORY
        value: $(Pipeline.Workspace)/.helmfile-toolchain
      - name: HELMFILE_VERSION
        value: "1.1.9"
      - name: HELMFILE_SHA256
        value: ee71196bb12460905b8cbe0ef67b28db51ef681b777cc212d8c0956475b51905
      - name: HELMFILE_TOOLCHAIN_CACHE_RESTORED
        value: "false"

    ${{ if eq(parameters.adoEnvironment, '') }}:
      steps:
        - template: /pipelines/steps/deploy-chart.yaml
          parameters:
            chart: ${{ parameters }}
    ${{ else }}:
      strategy:
        runOnce:
          deploy:
            steps:
              - download: none
              - template: /pipelines/steps/deploy-chart.yaml
                parameters:
                  chart: ${{ parameters }}
