parameters:
  - name: configurationDockerFile
    type: string
    default: configuration/Dockerfile
  - name: dockerFile
    type: string
    default: service/Dockerfile
  - name: migrations
    type: boolean
    default: false
  - name: serviceName
    type: string

jobs:
  - job: PackageJavaImage
    displayName: Package Java Image
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download service artifacts
        inputs:
          artifact: service
          path: service/target

      - template: /pipelines/steps/build-container-image.yaml@ipaffs-infra
        parameters:
          dockerFile: ${{ parameters.dockerFile }}
          directory: ./service
          imageName: ${{ parameters.serviceName }}

  - job: PackageMigrationsImage
    displayName: Package Migrations Image
    condition: ${{ eq(parameters.migrations, true) }}
    steps:
      - template: /pipelines/steps/build-container-image.yaml@ipaffs-infra
        parameters:
          dockerFile: ${{ parameters.configurationDockerFile }}
          directory: ./configuration
          imageName: ${{ parameters.serviceName }}-configuration

# vim: set ts=2 sts=2 sw=2 et:
