parameters:
  - name: dockerFile
    type: string
    default: Dockerfile
  - name: migrations
    type: boolean
    default: false
  - name: serviceName
    type: string

jobs:
  - job: PackageJavaImage
    displayName: Package Java Image

    steps:
      - checkout: self
        lfs: true

      - task: DownloadPipelineArtifact@2
        displayName: Download service artifacts
        inputs:
          artifact: service
          path: service/target

      - template: /pipelines/steps/build-container-image.yaml@ipaffs-infra
        parameters:
          dockerFile: service/${{ parameters.dockerFile }}
          directory: ./service
          imageName: ${{ parameters.serviceName }}

  - job: PackageMigrationsImage
    displayName: Package Migrations Image
    condition: and(not(failed()), not(canceled()), ${{ eq(parameters.migrations, true) }})
    steps:
      - checkout: self
        lfs: true

      - template: /pipelines/steps/build-container-image.yaml@ipaffs-infra
        parameters:
          dockerFile: configuration/${{ parameters.dockerFile }}
          directory: ./configuration
          imageName: ${{ parameters.serviceName }}-configuration

