---
image:
  repository: jetstack/cert-manager-controller

cainjector:
  image:
    repository: jetstack/cert-manager-cainjector

startupapicheck:
  image:
    repository: jetstack/cert-manager-startupapicheck

webhook:
  image:
    repository: jetstack/cert-manager-webhook

crds:
  enabled: true

