controller:
  enableSnippets: true
  extraArgs:
    update-status: ""
  replicaCount: 1
  nginxplus: false
  ingressClass: nginx
  allowSnippetAnnotations: true
  config:
    annotations-risk-level: Critical
  ingressClassResource:
    name: nginx
  readyStatus:
    initialDelaySeconds: 10
  service:
    enabled: true
    internal:
      enabled: true
      type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: 80
  image:
    digest: ""
    pullPolicy: Always
  admissionWebhooks:
    enabled: true
    patch:
      image:
        digest: ""

rbac:
  create: true
