apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service }}
  labels:
    {{- include "ipaffs-common.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "9"
data:
  ENVIRONMENT: "{{ .Values.environment }}"
{{- range $databaseName := .Values.database.databaseNames }}
{{- $db := dict "databaseName" $databaseName "Values" $.Values "Release" $.Release }}
  DATABASE_DB_CONNECTION_STRING_{{ upper (snakecase $databaseName) }}: "jdbc:sqlserver://{{ template "ipaffs-common.azure.sqlServerHostname" $db }}:1433;databaseName={{ template "ipaffs-common.azure.databaseName" $db }};encrypt=true;socketTimeout=1800000;loginTimeout=15;authentication=ActiveDirectoryManagedIdentity;msiClientId={{ $.Values.azure.clientId }}"
{{- end }}
  AZURE_SEARCH_DB_CONNECTION_STRING="Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Database=${DATABASE_DB_NAME};ResourceId=/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${AZURE_RESOURCE_GROUP_NAME}/providers/Microsoft.Sql/servers/${DATABASE_DB_NAME};"





  export AZURE_SEARCH_DB_CONNECTION_STRING="Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Database=${DATABASE_DB_NAME};ResourceId=/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${AZURE_RESOURCE_GROUP_NAME}/providers/Microsoft.Sql/servers/${DATABASE_DB_NAME};"
  export AZURE_SEARCH_USER_ASSIGNED_IDENTITY="/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${AZURE_RESOURCE_GROUP_NAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${AZURE_SEARCH_MANAGED_IDENTITY_PRINCIPAL_NAME}"

{{- range $key, $val := .Values.config }}
  {{ $key }}: "{{ $val }}"
{{- end }}

# vim: set ts=2 sts=2 sw=2 et:
