{{ if .Values.database.enabled }}
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: {{ .Values.resourceGroup }}
spec:
  location: {{ .Values.databaseRegion }}
---
apiVersion: sql.azure.com/v1api20211101
kind: Server
metadata:
  name: {{ .Values.databaseServer }}
spec:
  owner:
    name: {{ .Values.resourceGroup }}
  location: {{ .Values.databaseRegion }}
---
apiVersion: sql.azure.com/v1api20211101
kind: ServersDatabase
metadata:
  name: {{ .Values.name }}-{{ .Values.environment }}
  annotations:
    serviceoperator.azure.com/reconcile-policy: manage
spec:
  owner:
    name: {{ .Values.databaseServer }}
  collation: SQL_Latin1_General_CP1_CI_AS
  location: {{ .Values.databaseRegion }}
{{ end }}
