{{- if .Values.database.migrations.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ipaffs-common.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ include "webapp.azure.migrationsClientId" . | quote }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "10"
  name: "{{ .Values.service }}-migrations"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.service }}-migrations"
  labels:
    {{- include "ipaffs-common.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "11"
spec:
  template:
    metadata:
      name: "{{ .Values.service }}-migrations"
      labels:
        {{- include "ipaffs-common.labels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: "{{ .Values.service }}-migrations"
      shareProcessNamespace: true
      restartPolicy: Never
      containers:
        - name: database-migration
          image: "{{ .Values.database.migrations.image }}"
          {{- if .Values.database.migrations.command }}
          command: ["{{ .Values.database.migrations.command }}"]
          {{- end }}
          {{- if .Values.database.migrations.args }}
          args:
            {{- range .Values.database.migrations.args }}
            - "{{ . }}"
            {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: ipaffs-config
            - configMapRef:
                name: {{ .Values.service }}
            {{- if .Values.externalSecret.enabled }}
            - secretRef:
                name: {{ printf "%s-secrets" .Values.service }}
                optional: true
            {{- end }}
            {{- if .Values.redis.enabled }}
            - secretRef:
                name: {{ printf "%s-redis" .Values.service }}
            {{- end }}
            {{- if .Values.serviceBus.enabled }}
            - secretRef:
                name: {{ printf "%s-servicebus" .Values.service }}
            {{- end }}
          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- range $databaseName := .Values.database.databaseNames }}
          {{- $db := dict "databaseName" $databaseName "Values" $.Values "Release" $.Release }}
            - name: DATABASE_DB_CONNECTION_STRING_{{ upper (snakecase $databaseName) }}
              value: "jdbc:sqlserver://{{ template "ipaffs-common.azure.sqlServerHostname" $db }}:1433;databaseName={{ template "ipaffs-common.azure.databaseName" $db }};encrypt=true;socketTimeout=1800000;loginTimeout=15;authentication=ActiveDirectoryManagedIdentity;msiClientId={{ include "webapp.azure.migrationsClientId" $ }}"
          {{- if $.Values.search.enabled }}
            - name: AZURE_SEARCH_DB_CONNECTION_STRING_{{ upper (snakecase $databaseName) }}
              value: "Encrypt=True;Connection Timeout=30;Database={{ template "ipaffs-common.azure.databaseName" $db }};ResourceId=/subscriptions/{{ $.Values.search.subscriptionId | quote }}/resourceGroups/{{ $.Values.search.resourceGroupName | quote }}/providers/Microsoft.Sql/servers/{{ template "ipaffs-common.azure.sqlServer" . }};"
          {{- end }}
          {{- end }}
            - name: AZURE_SQL_SERVER_NAME
              value: {{ template "ipaffs-common.azure.sqlServer" . }}
          {{- if .Values.search.enabled }}
            - name: AZURE_SEARCH_SUBSCRIPTION_ID
              value: {{ .Values.search.subscriptionId | quote }}
            - name: AZURE_SEARCH_RESOURCE_GROUP_NAME
              value: {{ .Values.search.resourceGroupName | quote }}
            - name: AZURE_SEARCH_SERVICE_NAME
              value: {{ .Values.search.serviceName | quote }}
            - name: AZURE_SEARCH_PRINCIPAL_NAME
              value: {{ .Values.search.principalName | quote }}
            - name: AZURE_SEARCH_USER_ASSIGNED_IDENTITY
              value: "/subscriptions/{{ .Values.search.subscriptionId | quote }}/resourcegroups/{{ .Values.search.resourceGroupName | quote }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{ .Values.search.principalName | quote }}"

          {{- end }}
          {{- if .Values.storage.accountName }}
            - name: AZURE_STORAGE_ACCOUNT_NAME
              value: {{ .Values.storage.accountName | quote }}
          {{- end }}
            - name: BASE_SERVICE_DB_USER_AD
              value: {{ include "webapp.azure.servicePrincipalName" . | quote }}
            - name: MANAGED_IDENTITY_USER
              value: {{ include "webapp.azure.servicePrincipalName" . | quote }}
      {{- if .Values.database.databaseNames }}
      initContainers:
        - name: workload-identity-adal-bridge
          image: "manicminer/workload-identity-adal-bridge:0.4.1"
          restartPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "info"
      {{- end }}
{{- end }}

# vim: set ts=2 sts=2 sw=2 et:
