apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
  labels:
    {{- include "ipaffs-common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.service }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ipaffs-common.selectorLabels" . | nindent 4 }}

