parameters:
  - name: environmentName
    type: string

stages:
  - stage: ConfigureDeployment
    displayName: Configure deployment
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: ConfigureBicep
        displayName: Configure Bicep
        steps:
          - checkout: self

          - task: Bash@3
            name: GenerateBicepParams
            displayName: Generate Bicep Params
            inputs:
              targetType: inline
              script: |
                set -ex
                cat <<- 'EOF' >'$(Build.SourcesDirectory)/30-infra-runtime.bicepparam'
                using '30-infra.bicep'
                extends 'envs/${{ lower(parameters.environmentName) }}/30-infra.bicepparam'
                param entraGroups = {
                  searchContributors: {
                    id: '$(searchContributorsGroupId)'
                    name: '$(searchContributorsGroupName)'
                  }
                  searchReaders: {
                    id: '$(searchReadersGroupId)'
                    name: '$(searchReadersGroupName)'
                  }
                  sqlAdmins: {
                    id: '$(sqlAdminGroupId)'
                    name: '$(sqlAdminGroupName)'
                  }
                }
                EOF
                cat '$(Build.SourcesDirectory)/30-infra-runtime.bicepparam'

          - task: PublishPipelineArtifact@1
            displayName: Publish artifact
            inputs:
              artifactName: bicepparam
              targetPath: $(Build.SourcesDirectory)/30-infra-runtime.bicepparam

  - stage: DeployResourceGroup
    displayName: Deploy Resource Group
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: RunBicep
        displayName: Run Bicep
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: WhatIf - Resource Group
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment sub what-if \
                        --name "ResourceGroup-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --location $(location) \
                        --template-file bicep/10-resource-group.bicep \
                        --parameters bicep/envs/${{ lower(parameters.environmentName) }}/10-resource-group.bicepparam

                - task: AzureCLI@2
                  displayName: Deploy - ResourceGroup
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment sub create \
                        --name "ResourceGroup-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --location $(location) \
                        --template-file bicep/10-resource-group.bicep \
                        --parameters bicep/envs/${{ lower(parameters.environmentName) }}/10-resource-group.bicepparam


  - stage: DeployNetwork
    displayName: Deploy Network
    dependsOn: DeployResourceGroup
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: RunBicep
        displayName: Run Bicep
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: WhatIf - Network
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group what-if \
                        --name "Network-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/20-network.bicep \
                        --parameters bicep/envs/${{ lower(parameters.environmentName) }}/20-network.bicepparam

                - task: AzureCLI@2
                  displayName: Deploy - Network
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group create \
                        --name "Network-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/20-network.bicep \
                        --parameters bicep/envs/${{ lower(parameters.environmentName) }}/20-network.bicepparam

                - task: AzureCLI@2
                  displayName: Wait for Deployment - Network
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group wait \
                        --name "Network-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --created


  - stage: SaveNetworkDeploymentDetails
    displayName: Save network deployment details
    dependsOn: DeployNetwork
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: StoreLibraryVariables
        displayName: Store library variables
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: NetworkOutputs
            displayName: Network outputs
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            env:
              ADO_ORG_URL: $(System.CollectionUri)
              ADO_PROJECT: $(System.TeamProject)
              ADO_GROUP_NAME: ${{ parameters.environmentName }}
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
              DEPLOYMENT_NAME: Network-$(Build.BuildId)
              RESOURCE_GROUP: $(resourceGroupName)
              SUBSCRIPTION_ID: $(subscriptionId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -x
                scripts/pipeline/update-group-variable-from-deployment.sh vnetName vnetName


  - stage: EstablishPeering
    displayName: Establish Peering
    dependsOn: SaveNetworkDeploymentDetails
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: TriggerPeeringPipeline
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: Bash@3
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  env:
                    ADO_ORG_URL: $(System.CollectionUri)
                    ADO_PROJECT: $(System.TeamProject)
                    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
                    SUBSCRIPTION_NAME: $(subscriptionName)
                    TENANT_ID: $(tenantId)
                    VNET_NAME: $(vnetName)
                  inputs:
                    filePath: scripts/pipeline/trigger-peering-pipeline.sh


  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure
    dependsOn:
      - ConfigureDeployment
      - EstablishPeering
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: RunBicep
        displayName: Run Bicep
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: DownloadPipelineArtifact@2
                  displayName: Download artifact
                  inputs:
                    artifactName: bicepparam
                    targetPath: $(Build.SourcesDirectory)/bicep

                - task: AzureCLI@2
                  displayName: WhatIf - Infrastructure
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group what-if \
                        --name "Infrastructure-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/30-infra.bicep \
                        --parameters bicep/30-infra-runtime.bicepparam \
                        --parameters tenantId="$(tenantId)"

                - task: AzureCLI@2
                  displayName: Deploy - Infrastructure
                  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group create \
                        --name "Infrastructure-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/30-infra.bicep \
                        --parameters bicep/30-infra-runtime.bicepparam \
                        --parameters tenantId="$(tenantId)"

                - task: AzureCLI@2
                  displayName: Wait for Deployment - Infrastructure
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group wait \
                        --name "Infrastructure-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --created


  - stage: SaveInfrastructureDeploymentDetails
    displayName: Save infrastructure deployment details
    dependsOn: DeployInfrastructure
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: StoreLibraryVariables
        displayName: Store library variables
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: InfrastructureOutputs
            displayName: Infrastructure outputs
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            env:
              ADO_ORG_URL: $(System.CollectionUri)
              ADO_PROJECT: $(System.TeamProject)
              ADO_GROUP_NAME: ${{ parameters.environmentName }}
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
              DEPLOYMENT_NAME: Infrastructure-$(Build.BuildId)
              RESOURCE_GROUP: $(resourceGroupName)
              SUBSCRIPTION_ID: $(subscriptionId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -x
                scripts/pipeline/update-group-variable-from-deployment.sh acrLoginServer acrLoginServer
                scripts/pipeline/update-group-variable-from-deployment.sh acrName acrName
                scripts/pipeline/update-group-variable-from-deployment.sh azureServiceOperatorClientId azureServiceOperatorClientId
                scripts/pipeline/update-group-variable-from-deployment.sh externalSecretsClientId externalSecretsClientId
                scripts/pipeline/update-group-variable-from-deployment.sh aksOidcIssuer aksOidcIssuer
                scripts/pipeline/update-group-variable-from-deployment.sh keyVaultName keyVaultName
                scripts/pipeline/update-group-variable-from-deployment.sh keyVaultUrl keyVaultUri
                scripts/pipeline/update-group-variable-from-deployment.sh kubernetesCluster aksClusterName
                scripts/pipeline/update-group-variable-from-deployment.sh redisName redisName
                scripts/pipeline/update-group-variable-from-deployment.sh searchServiceName searchServiceName
                scripts/pipeline/update-group-variable-from-deployment.sh sqlServerName sqlServerName
                scripts/pipeline/update-group-variable-from-deployment.sh sqlServerManagedIdentityObjectId sqlServerManagedIdentityObjectId
                scripts/pipeline/update-group-variable-from-deployment.sh insightsInstrumentationKey insightsInstrumentationKey
                scripts/pipeline/update-group-variable-from-deployment.sh insightsConnectionString insightsConnectionString

# vim: set ts=2 sts=2 sw=2 et:
