parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC
  - name: serviceName
    displayName: ServiceName
    type: string

stages:
  - stage: DeployIdentities
    displayName: Deploy and configure identity infrastructure
    jobs:
      - job: MigrationsIdentity
        displayName: Set up Migrations Identity
        variables:
          - group: "${{ parameters.environmentName }}"
          - template: "/pipelines/vars/common.yaml"
          - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
          - name: lowerResourceGroupName
            value: $[lower(variables.resourceGroupName)]

        steps:
          - task: AzureCLI@2
            name: CreateIdentity
            displayName: Create Managed Identity and Federated Credential
            env:
              MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-ipaffs-dev-${{ parameters.serviceName }}-migrations
              RESOURCE_GROUP_NAME: $(resourceGroupName)
              AKS_CREDENTIAL: ${{ parameters.serviceName }}-migration
              AKS_ISSUER: $(aksOidcIssuer)
              AKS_AUDIENCES: "api://AzureADTokenExchange"
              AKS_SUBJECT: "system:serviceaccount:ipaffs-dev:${{ parameters.serviceName }}-migrations"
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: $(Build.SourcesDirectory)/ipaffs-infra/scripts/pipeline/create-identity.sh

          - task: AzureCLI@2
            name: AddToSQLAdminsGroup
            displayName: Add Managed Identity to SQL Admin Group
            env:
              GROUP_ID: $(sqlAdminGroupId)
              PRINCIPAL_ID: $(principalId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: $(Build.SourcesDirectory)/ipaffs-infra/scripts/pipeline/add-principal-to-group.sh

          - task: AzureCLI@2
            name: WaitForGroupMembership
            displayName: Wait for group membership
            env:
              GROUP_ID: $(sqlAdminGroupId)
              PRINCIPAL_ID: $(principalId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: $(Build.SourcesDirectory)/ipaffs-infra/scripts/pipeline/wait-for-group-membership.sh

      - job: ServiceIdentity
        displayName: Set up Service Identity
        variables:
          - group: "${{ parameters.environmentName }}"
          - template: "/pipelines/vars/common.yaml"
          - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
          - name: lowerResourceGroupName
            value: $[lower(variables.resourceGroupName)]

        steps:
          - task: AzureCLI@2
            name: CreateIdentity
            displayName: Create Managed Identity and Federated Credential
            env:
              MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-ipaffs-dev-${{ parameters.serviceName }}-service
              RESOURCE_GROUP_NAME: $(resourceGroupName)
              AKS_CREDENTIAL: ${{ parameters.serviceName }}-service
              AKS_ISSUER: $(aksOidcIssuer)
              AKS_AUDIENCES: "api://AzureADTokenExchange"
              AKS_SUBJECT: "system:serviceaccount:ipaffs-dev:${{ parameters.serviceName }}-service"
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: $(Build.SourcesDirectory)/ipaffs-infra/scripts/pipeline/create-identity.sh

# vim: set ts=2 sts=2 sw=2 et:
