parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC
  - name: serviceName
    displayName: ServiceName
    type: string

stages:
  - stage: DeployIdentities
    displayName: Deploy and configure identity infrastructure
    jobs:
      - job: MigrationsIdentity
        displayName: Set up Migrations Identity
        variables:
          - group: "${{ parameters.environmentName }}"
          - template: "/pipelines/vars/common.yaml"
          - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
          - name: lowerResourceGroupName
            value: $[lower(variables.resourceGroupName)]

        steps:
          - task: AzureCLI@2
            name: CreateIdentity
            displayName: Create Managed Identity and Federated Credential
            env:
              MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-migrations-${{ parameters.serviceName }}-ipaffs-dev
              RESOURCE_GROUP_NAME: $(resourceGroupName)
              AKS_MIGRATION_CREDENTIAL: ${{ parameters.serviceName }}-migration
              AKS_MIGRATION_ISSUER: $(aksMigrationIssuer)
              AKS_MIGRATION_AUDIENCES: "api://AzureADTokenExchange"
              AKS_MIGRATION_SUBJECT: "system:serviceaccount:ipaffs-dev:${{ parameters.serviceName }}-migrations"
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -eux
                az identity create --name "${MANAGED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP_NAME}"
                CLIENT_ID="$(az identity show --name "${MANAGED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --query clientId --output tsv)"
                PRINCIPAL_ID="$(az identity show --name "${MANAGED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --query principalId --output tsv)"
                az identity federated-credential create --identity-name "${MANAGED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --name "${AKS_MIGRATION_CREDENTIAL}" --issuer "${AKS_MIGRATION_ISSUER}" --audiences "${AKS_MIGRATION_AUDIENCES}" --subject "${AKS_MIGRATION_SUBJECT}"
                echo "##vso[task.setvariable variable=migrationsClientId;isOutput=true]$CLIENT_ID"
                echo "##vso[task.setvariable variable=principalId]$PRINCIPAL_ID"

          - task: AzureCLI@2
            name: AddToSQLAdminsGroup
            displayName: Add Managed Identity to SQL Admin Group
            env:
              SQL_ADMIN_GROUP_ID: $(sqlAdminGroupId)
              PRINCIPAL_ID: $(principalId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -ux
                max_attempts=10
                attempt=0
                while (( attempt < max_attempts )); do
                  RESULT="$(az ad group member add -g "${SQL_ADMIN_GROUP_ID}" --member-id "${PRINCIPAL_ID}" 2>&1)"
                  STATUS=$?
                  (( STATUS == 0 )) && exit 0
                  [[ "${RESULT}" =~ "One or more added object references already exist" ]] && exit 0
                  sleep 10
                done
                exit 1

          - task: AzureCLI@2
            name: WaitForGroupMembership
            displayName: Wait for group membership
            env:
              SQL_ADMIN_GROUP_ID: $(sqlAdminGroupId)
              PRINCIPAL_ID: $(principalId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -ux
                TOKEN="$(az account get-access-token --scope https://graph.microsoft.com/.default --query accessToken -o tsv)"
                [[ $? -ne 0 ]] && exit 1
                max_attempts=10
                successful=0
                attempt=0
                wait=2
                while (( attempt < max_attempts )); do
                  (( attempt++ ))
                  result="$(curl -w '%{http_code}' -s -o /dev/null -H "Authorization: Bearer ${TOKEN}" "https://graph.microsoft.com/v1.0/groups/${SQL_ADMIN_GROUP_ID}/members/${PRINCIPAL_ID}/\$ref")"
                  if [[ "${result}" == "200" ]]; then
                    (( successful++ ))
                    (( successful == 5 )) && exit 0
                    wait=2
                    sleep 5
                  else
                    successful=0
                    sleep $wait
                    (( wait*=2 ))
                    (( wait > 60 )) && wait=60
                  fi
                done
                exit 1

      - job: ServiceIdentity
        displayName: Set up Service Identity
        variables:
          - group: "${{ parameters.environmentName }}"
          - template: "/pipelines/vars/common.yaml"
          - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
          - name: lowerResourceGroupName
            value: $[lower(variables.resourceGroupName)]

        steps:
          - task: AzureCLI@2
            name: CreateIdentity
            displayName: Create Managed Identity and Federated Credential
            env:
              MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-service-${{ parameters.serviceName }}-ipaffs-dev
              RESOURCE_GROUP_NAME: $(resourceGroupName)
              AKS_MIGRATION_CREDENTIAL: ${{ parameters.serviceName }}-service
              AKS_MIGRATION_ISSUER: $(aksServiceIssuer)
              AKS_MIGRATION_AUDIENCES: "api://AzureADTokenExchange"
              AKS_MIGRATION_SUBJECT: "system:serviceaccount:ipaffs-dev:${{ parameters.serviceName }}-service"
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -eux
                az identity create --name "${MANAGED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP_NAME}"
                CLIENT_ID="$(az identity show --name "${MANAGED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --query clientId --output tsv)"
                PRINCIPAL_ID="$(az identity show --name "${MANAGED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --query principalId --output tsv)"
                az identity federated-credential create --identity-name "${MANAGED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --name "${AKS_MIGRATION_CREDENTIAL}" --issuer "${AKS_MIGRATION_ISSUER}" --audiences "${AKS_MIGRATION_AUDIENCES}" --subject "${AKS_MIGRATION_SUBJECT}"
                echo "##vso[task.setvariable variable=serviceClientId;isOutput=true]$CLIENT_ID"
                echo "##vso[task.setvariable variable=principalId]$PRINCIPAL_ID"

# vim: set ts=2 sts=2 sw=2 et:
