parameters:
  - name: environmentName
    type: string

stages:
  - stage: ConfigureInfraDeployment
    displayName: Configure deployment
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: ConfigureBicep
        displayName: Configure Bicep
        steps:
          - checkout: self

          - task: Bash@3
            name: GenerateBicepParams
            displayName: Generate Bicep Params
            inputs:
              targetType: inline
              script: |
                set -ex
                cat <<- 'EOF' >'$(Build.SourcesDirectory)/40-infra-runtime.bicepparam'
                using '40-infra.bicep'
                extends 'envs/${{ lower(parameters.environmentName) }}/40-infra.bicepparam'
                param entraGroups = {
                  aksAdmins: {
                    id: '$(aksAdminsGroupId)'
                    name: '$(aksAdminsGroupName)'
                  }
                  aksContributors: {
                    id: '$(aksContributorsGroupId)'
                    name: '$(aksContributorsGroupName)'
                  }
                  aksReaders: {
                    id: '$(aksReadersGroupId)'
                    name: '$(aksReadersGroupName)'
                  }
                  keyVaultAdmins: {
                    id: '$(keyVaultAdminsGroupId)'
                    name: '$(keyVaultAdminsGroupName)'
                  }
                  keyVaultSecretsReaders: {
                    id: '$(keyVaultSecretsReadersGroupId)'
                    name: '$(keyVaultSecretsReadersGroupName)'
                  }
                  searchContributors: {
                    id: '$(searchContributorsGroupId)'
                    name: '$(searchContributorsGroupName)'
                  }
                  searchReaders: {
                    id: '$(searchReadersGroupId)'
                    name: '$(searchReadersGroupName)'
                  }
                  blobStorageContributors: {
                    id: '$(blobStorageContributorsGroupId)'
                    name: '$(blobStorageContributorsGroupName)'
                  }
                  blobStorageReaders: {
                    id: '$(blobStorageReadersGroupId)'
                    name: '$(blobStorageReadersGroupName)'
                  }
                  sqlAdmins: {
                    id: '$(sqlAdminGroupId)'
                    name: '$(sqlAdminGroupName)'
                  }
                }
                EOF
                cat '$(Build.SourcesDirectory)/40-infra-runtime.bicepparam'

          - task: PublishPipelineArtifact@1
            displayName: Publish artifact
            inputs:
              artifactName: bicepparam-infra
              targetPath: $(Build.SourcesDirectory)/40-infra-runtime.bicepparam


  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure
    dependsOn: ConfigureInfraDeployment
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: RunBicep
        displayName: Run Bicep
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: DownloadPipelineArtifact@2
                  displayName: Download artifact
                  inputs:
                    artifactName: bicepparam-infra
                    targetPath: $(Build.SourcesDirectory)/bicep

                - task: AzureCLI@2
                  displayName: WhatIf - Infrastructure
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group what-if \
                        --name "Infrastructure-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/40-infra.bicep \
                        --parameters bicep/40-infra-runtime.bicepparam \
                        --parameters tenantId="$(tenantId)"

                - task: AzureCLI@2
                  displayName: Deploy - Infrastructure
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group create \
                        --name "Infrastructure-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/40-infra.bicep \
                        --parameters bicep/40-infra-runtime.bicepparam \
                        --parameters tenantId="$(tenantId)"

                - task: AzureCLI@2
                  displayName: Wait for Deployment - Infrastructure
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group wait \
                        --name "Infrastructure-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --created


  - stage: SaveInfrastructureDeploymentDetails
    displayName: Save infrastructure deployment details
    dependsOn: DeployInfrastructure
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: StoreLibraryVariables
        displayName: Store library variables
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: InfrastructureOutputs
            displayName: Infrastructure outputs
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            env:
              ADO_ORG_URL: $(System.CollectionUri)
              ADO_PROJECT: $(System.TeamProject)
              ADO_GROUP_NAME: ${{ parameters.environmentName }}
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
              DEPLOYMENT_NAME: Infrastructure-$(Build.BuildId)
              RESOURCE_GROUP: $(resourceGroupName)
              SUBSCRIPTION_ID: $(subscriptionId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -x
                scripts/pipeline/update-group-variable-from-deployment.sh acrLoginServer acrLoginServer
                scripts/pipeline/update-group-variable-from-deployment.sh acrName acrName
                scripts/pipeline/update-group-variable-from-deployment.sh azureServiceOperatorClientId azureServiceOperatorClientId
                scripts/pipeline/update-group-variable-from-deployment.sh externalSecretsClientId externalSecretsClientId
                scripts/pipeline/update-group-variable-from-deployment.sh aksOidcIssuer aksOidcIssuer
                scripts/pipeline/update-group-variable-from-deployment.sh keyVaultName keyVaultName
                scripts/pipeline/update-group-variable-from-deployment.sh keyVaultUrl keyVaultUri
                scripts/pipeline/update-group-variable-from-deployment.sh kubernetesCluster aksClusterName
                scripts/pipeline/update-group-variable-from-deployment.sh redisName redisName
                scripts/pipeline/update-group-variable-from-deployment.sh searchServiceSubscriptionId searchServiceSubscriptionId
                scripts/pipeline/update-group-variable-from-deployment.sh searchServiceResourceGroupName searchServiceResourceGroupName
                scripts/pipeline/update-group-variable-from-deployment.sh searchServiceName searchServiceName
                scripts/pipeline/update-group-variable-from-deployment.sh searchServiceManagedIdentityPrincipalId searchServiceManagedIdentityPrincipalId
                scripts/pipeline/update-group-variable-from-deployment.sh searchServiceManagedIdentityPrincipalName searchServiceManagedIdentityPrincipalName
                scripts/pipeline/update-group-variable-from-deployment.sh sqlServerName sqlServerName
                scripts/pipeline/update-group-variable-from-deployment.sh sqlServerManagedIdentityObjectId sqlServerManagedIdentityObjectId
                scripts/pipeline/update-group-variable-from-deployment.sh storageAccountName storageAccountName
                scripts/pipeline/update-group-variable-from-deployment.sh insightsConnectionString insightsConnectionString
                scripts/pipeline/update-group-variable-from-deployment.sh insightsInstrumentationKey insightsInstrumentationKey

# vim: set ts=2 sts=2 sw=2 et:
