parameters:
  - name: environmentName
    type: string

stages:
  - stage: ConfigurePrivateLinkDeployment
    displayName: Configure deployment
    variables:
      - group: Common
      - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
        - group: HigherEnvs
      - ${{ else }}:
        - group: LowerEnvs
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: ConfigureBicep
        displayName: Configure Bicep
        steps:
          - checkout: self

          - task: Bash@3
            name: GenerateBicepParams
            displayName: Generate Bicep Params
            inputs:
              targetType: inline
              script: |
                set -ex
                cat <<- 'EOF' >'$(Build.SourcesDirectory)/50-privatelink-runtime.bicepparam'
                using '50-privatelink.bicep'
                extends 'envs/${{ lower(parameters.environmentName) }}/50-privatelink.bicepparam'
                param subnets = {
                  privateEndpoints: {
                    id: '$(privateEndpointsSubnetId)'
                    name: '$(privateEndpointsSubnetName)'
                  }
                }
                EOF
                cat '$(Build.SourcesDirectory)/50-privatelink-runtime.bicepparam'

          - task: PublishPipelineArtifact@1
            displayName: Publish artifact
            inputs:
              artifactName: bicepparam-privatelink
              targetPath: $(Build.SourcesDirectory)/50-privatelink-runtime.bicepparam


  - stage: DeployPrivateLink
    displayName: Deploy Private Link
    variables:
      - group: Common
      - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
        - group: HigherEnvs
      - ${{ else }}:
        - group: LowerEnvs
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: RunBicep
        displayName: Run Bicep
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: DownloadPipelineArtifact@2
                  displayName: Download artifact
                  inputs:
                    artifactName: bicepparam-privatelink
                    targetPath: $(Build.SourcesDirectory)/bicep

                - task: AzureCLI@2
                  displayName: WhatIf - PrivateLink
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group what-if \
                        --name "PrivateLink-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/50-privatelink.bicep \
                        --parameters bicep/50-privatelink-runtime.bicepparam

                - task: AzureCLI@2
                  displayName: Deploy - PrivateLink
                  condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group create \
                        --name "PrivateLink-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/50-privatelink.bicep \
                        --parameters bicep/50-privatelink-runtime.bicepparam

                - task: AzureCLI@2
                  displayName: Wait for Deployment - PrivateLink
                  condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group wait \
                        --name "PrivateLink-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --created

# vim: set ts=2 sts=2 sw=2 et:
