parameters:
  - name: environmentName
    type: string

stages:
  - stage: DeployNetwork
    displayName: Deploy Network
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: RunBicep
        displayName: Run Bicep
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: WhatIf - Network
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group what-if \
                        --name "Network-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/20-network.bicep \
                        --parameters bicep/envs/${{ lower(parameters.environmentName) }}/20-network.bicepparam

                - task: AzureCLI@2
                  displayName: Deploy - Network
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group create \
                        --name "Network-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/20-network.bicep \
                        --parameters bicep/envs/${{ lower(parameters.environmentName) }}/20-network.bicepparam

                - task: AzureCLI@2
                  displayName: Wait for Deployment - Network
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az deployment group wait \
                        --name "Network-$(Build.BuildId)" \
                        --subscription $(subscriptionId) \
                        --resource-group $(resourceGroupName) \
                        --created


  - stage: SaveNetworkDeploymentDetails
    displayName: Save network deployment details
    dependsOn: DeployNetwork
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: StoreLibraryVariables
        displayName: Store library variables
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: NetworkOutputs
            displayName: Network outputs
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            env:
              ADO_ORG_URL: $(System.CollectionUri)
              ADO_PROJECT: $(System.TeamProject)
              ADO_GROUP_NAME: ${{ parameters.environmentName }}
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
              DEPLOYMENT_NAME: Network-$(Build.BuildId)
              RESOURCE_GROUP: $(resourceGroupName)
              SUBSCRIPTION_ID: $(subscriptionId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -x
                scripts/pipeline/update-group-variable-from-deployment.sh vnetName vnetName


  - stage: EstablishPeering
    displayName: Establish Peering
    dependsOn: SaveNetworkDeploymentDetails
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: TriggerPeeringPipeline
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: Bash@3
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  env:
                    ADO_ORG_URL: $(System.CollectionUri)
                    ADO_PROJECT: $(System.TeamProject)
                    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
                    SUBSCRIPTION_NAME: $(subscriptionName)
                    TENANT_ID: $(tenantId)
                    VNET_NAME: $(vnetName)
                  inputs:
                    filePath: scripts/pipeline/trigger-peering-pipeline.sh

# vim: set ts=2 sts=2 sw=2 et:
