parameters:
  - name: environmentName
    type: string

stages:
  - stage: CreateUserGroups
    displayName: Create Entra User Groups
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: TeamGroups
        displayName: Team Groups
        #condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        variables:
          - name: adminsGroupName
            value: AAG-Users-IPAFFS-ProjAdmins
          - name: developersGroupName
            value: AAG-Users-IPAFFS-Developers
          - name: readersGroupName
            value: AAG-Users-IPAFFS-Readers
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: AdminsGroupDelete
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -x
                TOKEN="$(az account get-access-token --scope https://graph.microsoft.com/.default --query accessToken -o tsv)"
                [[ $? -ne 0 ]] && exit 1
                groupResult="$(curl -X DELETE -H "Authorization: Bearer ${TOKEN}" https://graph.microsoft.com/v1.0/groups/139a07e1-02c0-49ce-a9cf-4b0f5b582426)"
                [[ $? -ne 0 ]] && exit 1
                errorCode="$(jq -r '.error.code' <<<"${groupResult}")"
                [[ "${errorCode}" == "null" ]] || [[ "${errorCode}" == "" ]] || exit 1

          - task: AzureCLI@2
            name: AdminsGroup
            env:
              GROUP_NAME: $(adminsGroupName)
              GROUP_DESCRIPTION: Entra user group for IPAFFS Project Admins
              GROUP_OWNER_OBJECT_IDS: $(groupOwnerObjectIds)
              GROUP_ID: 139a07e1-02c0-49ce-a9cf-4b0f5b582426
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh

          - task: AzureCLI@2
            name: AdminsMembers
            env:
              GROUP_NAME: $(adminsGroupName)
              GROUP_MEMBERS: $(adminsGroupMembers)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/set-entra-group-members.sh

          - task: AzureCLI@2
            name: DevelopersGroup
            env:
              GROUP_NAME: $(developersGroupName)
              GROUP_DESCRIPTION: Entra user group for IPAFFS Developers
              GROUP_OWNER_OBJECT_IDS: $(groupOwnerObjectIds)
              GROUP_ID: a0fecc06-e286-4264-8bc0-980da0189a29
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh

          - task: AzureCLI@2
            name: DevelopersMembers
            env:
              GROUP_NAME: $(developersGroupName)
              GROUP_MEMBERS: $(developersGroupMembers)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/set-entra-group-members.sh

          - task: AzureCLI@2
            name: ReadersGroup
            env:
              GROUP_NAME: $(readersGroupName)
              GROUP_DESCRIPTION: Entra user group for IPAFFS Readers
              GROUP_OWNER_OBJECT_IDS: $(groupOwnerObjectIds)
              GROUP_ID: eef5a29d-607a-43fd-96a8-664e51165878
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh

          - task: AzureCLI@2
            name: ReadersMembers
            env:
              GROUP_NAME: $(readersGroupName)
              GROUP_MEMBERS: $(readersGroupMembers)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/set-entra-group-members.sh


  - stage: CreateAccessGroups
    displayName: Create Entra Access Groups
    dependsOn: CreateUserGroups
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
      - name: teamAdminsObjectId
        value: $[stageDependencies.CreateUserGroups.TeamGroups.outputs['AdminsGroup.objectId']]
    jobs:
      - job: SearchGroups
        displayName: Search Service Groups
        #condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        variables:
          - name: contributorsGroupName
            value: AG-Azure-IMP_${{ parameters.environmentName }}-SearchContributors
          - name: readersGroupName
            value: AG-Azure-IMP_${{ parameters.environmentName }}-SearchReaders
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: SearchContributors
            env:
              GROUP_NAME: $(contributorsGroupName)
              GROUP_DESCRIPTION: Entra access group for IPAFFS Search Services Contributors
              GROUP_OWNER_OBJECT_IDS: $(groupOwnerObjectIds)
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh

          - task: AzureCLI@2
            name: SearchContributorsMember
            env:
              GROUP_ID: $(SearchContributors.objectId)
              PRINCIPAL_ID: $(teamAdminsObjectId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/add-principal-to-group.sh

          - task: AzureCLI@2
            name: SearchReaders
            env:
              GROUP_NAME: $(readersGroupName)
              GROUP_DESCRIPTION: Entra access group for IPAFFS Search Services Readers
              GROUP_OWNER_OBJECT_IDS: $(groupOwnerObjectIds)
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh

      - job: SQLGroups
        displayName: SQL Groups
        #condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        variables:
          - name: groupName
            value: AG-Azure-IMP_${{ parameters.environmentName }}-SQLAdmins
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: SQLAdmins
            env:
              GROUP_NAME: $(groupName)
              GROUP_DESCRIPTION: Entra access group for IPAFFS SQL Admins
              GROUP_OWNER_OBJECT_IDS: $(groupOwnerObjectIds)
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh

          - task: AzureCLI@2
            name: SQLAdminsMember
            env:
              GROUP_ID: $(SQLAdmins.objectId)
              PRINCIPAL_ID: $(teamAdminsObjectId)
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/add-principal-to-group.sh


  - stage: SaveGroupDetails
    displayName: Save group details
    dependsOn: CreateAccessGroups
    #condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
      - name: searchContributorsDisplayName
        value: $[stageDependencies.CreateAccessGroups.SearchGroups.outputs['SearchContributors.displayName']]
      - name: searchContributorsObjectId
        value: $[stageDependencies.CreateAccessGroups.SearchGroups.outputs['SearchContributors.objectId']]
      - name: searchReadersDisplayName
        value: $[stageDependencies.CreateAccessGroups.SearchGroups.outputs['SearchReaders.displayName']]
      - name: searchReadersObjectId
        value: $[stageDependencies.CreateAccessGroups.SearchGroups.outputs['SearchReaders.objectId']]
      - name: sqlAdminsDisplayName
        value: $[stageDependencies.CreateAccessGroups.SQLGroups.outputs['SQLAdmins.displayName']]
      - name: sqlAdminsObjectId
        value: $[stageDependencies.CreateAccessGroups.SQLGroups.outputs['SQLAdmins.objectId']]
    jobs:
      - job: UpdateGroupVariables
        displayName: Update group variables
        steps:
          - task: AzureCLI@2
            name: StoreLibraryVars
            displayName: Store Library Variables
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            env:
              ADO_ORG_URL: $(System.CollectionUri)
              ADO_PROJECT: $(System.TeamProject)
              ADO_GROUP_NAME: ${{ parameters.environmentName }}
            inputs:
              # TODO: fix this for all envs
              azureSubscription: ADO-DefraGovUK-AZR-POC_IMP
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -x
                scripts/pipeline/update-group-variable.sh searchContributorsGroupId '$(searchContributorsObjectId)'
                scripts/pipeline/update-group-variable.sh searchContributorsGroupName '$(searchContributorsDisplayName)'
                scripts/pipeline/update-group-variable.sh searchReadersGroupId '$(searchReadersObjectId)'
                scripts/pipeline/update-group-variable.sh searchReadersGroupName '$(searchReadersDisplayName)'
                scripts/pipeline/update-group-variable.sh sqlAdminGroupId '$(sqlAdminsObjectId)'
                scripts/pipeline/update-group-variable.sh sqlAdminGroupName '$(sqlAdminsDisplayName)'

# vim: set ts=2 sts=2 sw=2 et:
