parameters:
  - name: environmentName
    type: string

stages:
  - stage: CreateEntraGroups
    displayName: Create Entra Groups
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: LookupServicePrincipals
        displayName: Look up service principals
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: ServiceConnection
            displayName: Local Service Connection
            env:
              OBJECT_NAME: $(serviceConnection)
              OBJECT_TYPE: servicePrincipal
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/lookup-directory-object.sh

      - job: SearchGroups
        displayName: Search Service Groups
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        dependsOn: LookupServicePrincipals
        variables:
          - name: contributorsGroupName
            value: AG-Azure-IMP_${{ parameters.environmentName }}-SearchContributors
          - name: readersGroupName
            value: AG-Azure-IMP_${{ parameters.environmentName }}-SearchReaders
          - name: serviceConnectionObjectId
            value: $[dependencies.LookupServicePrincipals.outputs['ServiceConnection.objectId']]
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: SearchContributors
            env:
              GROUP_NAME: $(contributorsGroupName)
              GROUP_DESCRIPTION: Entra access group for IPAFFS Search Services Contributors
              GROUP_OWNER_OBJECT_IDS: $(serviceConnectionObjectId)
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh

          - task: AzureCLI@2
            name: SearchReaders
            env:
              GROUP_NAME: $(readersGroupName)
              GROUP_DESCRIPTION: Entra access group for IPAFFS Search Services Readers
              GROUP_OWNER_OBJECT_IDS: $(serviceConnectionObjectId)
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh

      - job: SQLGroups
        displayName: SQL Groups
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        dependsOn: LookupServicePrincipals
        variables:
          - name: groupName
            value: AG-Azure-IMP_${{ parameters.environmentName }}-SQLAdmins
          - name: serviceConnectionObjectId
            value: $[dependencies.LookupServicePrincipals.outputs['ServiceConnection.objectId']]
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: SQLAdmins
            env:
              GROUP_NAME: $(groupName)
              GROUP_DESCRIPTION: Entra access group for IPAFFS SQL Admins
              GROUP_OWNER_OBJECT_IDS: $(serviceConnectionObjectId)
            inputs:
              azureSubscription: $(upstreamServiceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/create-entra-group.sh


  - stage: SaveGroupDetails
    displayName: Save group details
    dependsOn: CreateEntraGroups
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
      - name: searchContributorsDisplayName
        value: $[stageDependencies.CreateEntraGroups.SearchGroups.outputs['SearchContributors.displayName']]
      - name: searchContributorsObjectId
        value: $[stageDependencies.CreateEntraGroups.SearchGroups.outputs['SearchContributors.objectId']]
      - name: searchReadersDisplayName
        value: $[stageDependencies.CreateEntraGroups.SearchGroups.outputs['SearchReaders.displayName']]
      - name: searchReadersObjectId
        value: $[stageDependencies.CreateEntraGroups.SearchGroups.outputs['SearchReaders.objectId']]
      - name: sqlAdminsDisplayName
        value: $[stageDependencies.CreateEntraGroups.SQLGroups.outputs['SQLAdmins.displayName']]
      - name: sqlAdminsObjectId
        value: $[stageDependencies.CreateEntraGroups.SQLGroups.outputs['SQLAdmins.objectId']]
    jobs:
      - job: UpdateGroupVariables
        displayName: Update group variables
        steps:
          - task: AzureCLI@2
            name: StoreLibraryVars
            displayName: Store Library Variables
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            env:
              ADO_ORG_URL: $(System.CollectionUri)
              ADO_PROJECT: $(System.TeamProject)
              ADO_GROUP_NAME: ${{ parameters.environmentName }}
            inputs:
              # TODO: fix this for all envs
              azureSubscription: ADO-DefraGovUK-AZR-POC_IMP
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -x
                scripts/pipeline/update-group-variable.sh searchContributorsGroupId '$(searchContributorsObjectId)'
                scripts/pipeline/update-group-variable.sh searchContributorsGroupName '$(searchContributorsDisplayName)'
                scripts/pipeline/update-group-variable.sh searchReadersGroupId '$(searchReadersObjectId)'
                scripts/pipeline/update-group-variable.sh searchReadersGroupName '$(searchReadersDisplayName)'
                scripts/pipeline/update-group-variable.sh sqlAdminGroupId '$(sqlAdminsObjectId)'
                scripts/pipeline/update-group-variable.sh sqlAdminGroupName '$(sqlAdminsDisplayName)'

# vim: set ts=2 sts=2 sw=2 et:
