parameters:
  - name: environmentName
    type: string

stages:
  - stage: InfraPermissions
    displayName: Infrastructure Permissions
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - deployment: GroupMemberships
        displayName: Group Memberships
        environment:
          name: "${{ parameters.environmentName }}"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  name: AddToDirectoryReadersGroup
                  displayName: Add SQL Server Managed Identity to Directory Readers Group
                  env:
                    GROUP_ID: $(directoryReadersGroupObjectId)
                    PRINCIPAL_ID: $(sqlServerManagedIdentityObjectId)
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptPath: scripts/pipeline/add-principal-to-group.sh

# vim: set ts=2 sts=2 sw=2 et:
