parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

stages:
  - stage: InfraPermissions
    displayName: Set up Infrastructure Permissions
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
    jobs:
      - job: LookupPrincipals
        displayName: Look up principals
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: DirectoryReadersGroup
            displayName: AG-AAD-Azure-Managed-Identities-Directory-Readers
            env:
              OBJECT_NAME: AG-AAD-Azure-Managed-Identities-Directory-Readers
              OBJECT_TYPE: group
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptPath: scripts/pipeline/lookup-directory-object.sh

      - deployment: GroupMemberships
        displayName: Group Memberships
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        dependsOn: LookupPrincipals
        environment:
          name: "${{ parameters.environmentName }}"
        variables:
          - name: directoryReadersGroupId
            value: $[dependencies.LookupPrincipals.outputs['DirectoryReadersGroup.objectId']]
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  name: AddToDirectoryReadersGroup
                  displayName: Add SQL Server Managed Identity to Directory Readers Group
                  env:
                    GROUP_ID: $(directoryReadersGroupId)
                    PRINCIPAL_ID: $(sqlServerManagedIdentityObjectId)
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptPath: scripts/pipeline/add-principal-to-group.sh

# vim: set ts=2 sts=2 sw=2 et:
