parameters:
  - name: environmentName
    type: string

stages:
  - stage: DeployHelmCharts
    displayName: Deploy Helm Charts
    jobs:
      - deployment: DeployHelm
        displayName: Deploy with Helm
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  name: AuthenticateAzure
                  displayName: Authenticate with Azure
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      az aks install-cli
                      az aks get-credentials -n "$(kubernetesCluster)" -g "$(resourceGroupName)" --subscription "$(subscriptionName)"
                      az acr login --name "$(acrName)"

                # See https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration?pivots=nginx-ingress-controller
                - task: AzureCLI@2
                  displayName: Helm Install - app-routing-controller
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      helm upgrade \
                        --install \
                        --debug \
                        --namespace app-routing-namespace \
                        --create-namespace \
                        --dependency-update \
                        --timeout 2m \
                        $(helmDryRun) \
                        app-routing-controller ./helm-charts/app-routing-controller

                - task: AzureCLI@2
                  displayName: Helm Install - cert-manager
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      helm upgrade \
                        --install \
                        --debug \
                        --namespace cert-manager \
                        --create-namespace \
                        --dependency-update \
                        --timeout 2m \
                        $(helmDryRun) \
                        --values helm-charts/cert-manager-values.yaml \
                        --set image.registry="$(acrLoginServer)" \
                        --set cainjector.image.registry="$(acrLoginServer)" \
                        --set startupapicheck.image.registry="$(acrLoginServer)" \
                        --set webhook.image.registry="$(acrLoginServer)" \
                        cert-manager "oci://quay.io/jetstack/charts/cert-manager" \
                        --version 1.19.1

                - task: AzureCLI@2
                  displayName: Helm Install - azure-service-operator-config
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      helm upgrade \
                        --install \
                        --debug \
                        --namespace azureserviceoperator-system \
                        --create-namespace \
                        --dependency-update \
                        --timeout 2m \
                        $(helmDryRun) \
                        --values helm-charts/azure-service-operator-config-values.yaml \
                        --set azureSubscriptionID="$(subscriptionId)" \
                        --set azureTenantID="$(tenantId)" \
                        --set azureClientID="$(azureServiceOperatorClientId)" \
                        azure-service-operator-config ./helm-charts/azure-service-operator-config

                - task: AzureCLI@2
                  displayName: Helm Install - azure-service-operator
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      helm upgrade \
                        --install \
                        --debug \
                        --namespace azureserviceoperator-system \
                        --create-namespace \
                        --dependency-update \
                        --timeout 2m \
                        $(helmDryRun) \
                        --values helm-charts/azure-service-operator-values.yaml \
                        --set image.repositoryBase="$(acrLoginServer)/k8s/azureserviceoperator" \
                        azure-service-operator azure-service-operator \
                        --repo "https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts" \
                        --version 2.16.0

                - task: AzureCLI@2
                  displayName: Helm Install - external-secrets
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      helm upgrade \
                        --install \
                        --debug \
                        --namespace external-secrets \
                        --create-namespace \
                        --dependency-update \
                        --timeout 2m \
                        $(helmDryRun) \
                        --values helm-charts/external-secrets-values.yaml \
                        --set azure.vaultUrl="$(keyVaultUrl)" \
                        --set azure.tenantId="$(tenantId)" \
                        --set azure.identityId="$(externalSecretsClientId)" \
                        --set serviceAccount.annotations.azure\\.workload\\.identity/client-id="$(externalSecretsClientId)" \
                        --set image.repository="$(acrLoginServer)/external-secrets/external-secrets" \
                        --set webhook.image.repository="$(acrLoginServer)/external-secrets/external-secrets" \
                        --set certController.image.repository="$(acrLoginServer)/external-secrets/external-secrets" \
                        external-secrets external-secrets \
                        --repo "https://charts.external-secrets.io" \
                        --version v1.1.1

                - task: AzureCLI@2
                  displayName: Helm Install - external-secrets-azure
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      helm upgrade \
                        --install \
                        --debug \
                        --namespace external-secrets \
                        --create-namespace \
                        --dependency-update \
                        --timeout 2m \
                        $(helmDryRun) \
                        --values helm-charts/external-secrets-values.yaml \
                        --set azure.vaultUrl="$(keyVaultUrl)" \
                        --set azure.tenantId="$(tenantId)" \
                        --set azure.identityId="$(externalSecretsClientId)" \
                        --set azure.serviceAccountRef.name=external-secrets \
                        --set azure.serviceAccountRef.namespace=external-secrets \
                        external-secrets-azure ./helm-charts/external-secrets-azure

                - task: AzureCLI@2
                  displayName: Helm Install - keda
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -x
                      helm upgrade \
                        --install \
                        --debug \
                        --namespace keda \
                        --create-namespace \
                        --dependency-update \
                        --timeout 2m \
                        $(helmDryRun) \
                        --values helm-charts/keda-values.yaml \
                        keda keda \
                        --repo "https://kedacore.github.io/charts"

# vim: set ts=2 sts=2 sw=2 et:
