parameters:
  - name: environmentName
    type: string

stages:
  - stage: DeployHelmCharts
    displayName: Deploy Helm Charts
    jobs:
      - deployment: DeployHelm
        displayName: Deploy with Helm
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: Set Azure subscription
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: az account set -s $(subscriptionName)

                # See https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration?pivots=nginx-ingress-controller
                - task: HelmDeploy@0
                  displayName: Helm Install - app-routing-controller
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: $(serviceConnection)
                    azureResourceGroup: $(resourceGroupName)
                    kubernetesCluster: $(kubernetesCluster)
                    namespace: app-routing-namespace
                    command: upgrade
                    chartName: helm-charts/app-routing-controller
                    releaseName: app-routing-controller
                    install: true
                    useClusterAdmin: true
                    arguments: >-
                      --dependency-update
                      --create-namespace

                - task: HelmDeploy@0
                  displayName: Helm Install - cert-manager
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: $(serviceConnection)
                    azureResourceGroup: $(resourceGroupName)
                    kubernetesCluster: $(kubernetesCluster)
                    namespace: cert-manager
                    command: upgrade
                    chartName: "oci://quay.io/jetstack/charts/cert-manager"
                    chartVersion: 1.19.1
                    releaseName: cert-manager
                    install: true
                    useClusterAdmin: true
                    arguments: >-
                      -f helm-charts/cert-manager-values.yaml
                      --create-namespace
                      --set image.registry=$(acrLoginServer)
                      --set cainjector.image.registry=$(acrLoginServer)
                      --set startupapicheck.image.registry=$(acrLoginServer)
                      --set webhook.image.registry=$(acrLoginServer)
                      $(helmDryRun)

                - task: HelmDeploy@0
                  displayName: Helm Install - azure-service-operator-config
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: $(serviceConnection)
                    azureResourceGroup: $(resourceGroupName)
                    kubernetesCluster: $(kubernetesCluster)
                    namespace: azureserviceoperator-system
                    command: upgrade
                    chartName: ./helm-charts/azure-service-operator-config
                    releaseName: azure-service-operator-config
                    install: true
                    useClusterAdmin: true
                    arguments: >-
                      -f helm-charts/azure-service-operator-config-values.yaml
                      --create-namespace
                      --set azureSubscriptionID=$(subscriptionId)
                      --set azureTenantID=$(tenantId)
                      --set azureClientID=$(azureServiceOperatorClientId)
                      $(helmDryRun)

                - task: HelmDeploy@0
                  displayName: Helm Install - azure-service-operator
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: $(serviceConnection)
                    azureResourceGroup: $(resourceGroupName)
                    kubernetesCluster: $(kubernetesCluster)
                    namespace: azureserviceoperator-system
                    command: upgrade
                    chartName: azure-service-operator
                    chartVersion: 2.16.0
                    releaseName: azure-service-operator
                    install: true
                    useClusterAdmin: true
                    arguments: >-
                      --repo https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts
                      -f helm-charts/azure-service-operator-values.yaml
                      --create-namespace
                      --set image.repositoryBase=$(acrLoginServer)/k8s/azureserviceoperator
                      $(helmDryRun)

                - task: HelmDeploy@0
                  displayName: Helm Install - external-secrets
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: $(serviceConnection)
                    azureResourceGroup: $(resourceGroupName)
                    kubernetesCluster: $(kubernetesCluster)
                    namespace: external-secrets
                    command: upgrade
                    chartName: "external-secrets"
                    chartVersion: v1.1.1
                    releaseName: external-secrets
                    install: true
                    useClusterAdmin: true
                    arguments: >-
                      --repo https://charts.external-secrets.io
                      -f helm-charts/external-secrets-values.yaml
                      --create-namespace
                      --set azure.vaultUrl=$(keyVaultUrl)
                      --set azure.tenantId=$(tenantId)
                      --set azure.identityId=$(externalSecretsClientId)
                      --set serviceAccount.annotations.azure\.workload\.identity/client-id=$(externalSecretsClientId)
                      --set image.repository=$(acrLoginServer)/external-secrets/external-secrets
                      --set webhook.image.repository=$(acrLoginServer)/external-secrets/external-secrets
                      --set certController.image.repository=$(acrLoginServer)/external-secrets/external-secrets
                      $(helmDryRun)

                - task: HelmDeploy@0
                  displayName: Helm Install - external-secrets-azure
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: $(serviceConnection)
                    azureResourceGroup: $(resourceGroupName)
                    kubernetesCluster: $(kubernetesCluster)
                    namespace: external-secrets
                    command: upgrade
                    chartName: ./helm-charts/external-secrets-azure
                    releaseName: external-secrets-azure
                    install: true
                    useClusterAdmin: true
                    arguments: >-
                      -f helm-charts/external-secrets-values.yaml
                      --create-namespace
                      --set azure.vaultUrl=$(keyVaultUrl)
                      --set azure.tenantId=$(tenantId)
                      --set azure.identityId=$(externalSecretsClientId)
                      --set azure.serviceAccountRef.name=external-secrets
                      --set azure.serviceAccountRef.namespace=external-secrets
                      $(helmDryRun)

# vim: set ts=2 sts=2 sw=2 et:
