parameters:
  - name: environmentName
    type: string

stages:
  - stage: PrivateLinkDNSRecords
    displayName: Set Private Endpoint DNS Records
    variables:
      - group: Common
      - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
        - group: HigherEnvs
      - ${{ else }}:
        - group: LowerEnvs
      - group: "${{ parameters.environmentName }}"
      - template: "vars/common.yaml"
      - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
      - template: /templates/vars/common.yaml@PipelineCommon
      - template: /templates/vars/regional/northeurope.yaml@PipelineCommon
    jobs:
      - deployment: ContainerRegistry
        displayName: Container Registry
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(acrName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

      - deployment: KeyVault
        displayName: Key Vault
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(keyVaultName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

      - deployment: Redis
        displayName: Redis
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(redisName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

      - deployment: RedisClassic
        displayName: Redis (Classic)
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(classicServiceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(classicResourceGroupName)'
                          -ResourceName '$(classicRedisName)'
                          -Subscription '$(classicSubscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

      - deployment: Search
        displayName: Search
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(searchServiceName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

      - deployment: SearchClassic
        displayName: Search (Classic)
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(classicServiceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(classicResourceGroupName)'
                          -ResourceName '$(classicSearchServiceName)'
                          -Subscription '$(classicSubscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

      - deployment: Storage
        displayName: Storage
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(storageAccountName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

      - deployment: SQLServer
        displayName: SQL Server
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(sqlServerName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

      - deployment: SQLServerClassic
        displayName: SQL Server (Classic)
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(classicServiceConnection)
                    scriptsList:
                      - displayName: "Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(classicResourceGroupName)'
                          -ResourceName '$(classicSqlServerName)'
                          -Subscription '$(classicSubscriptionName)'

                      - displayName: "Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

# vim: set ts=2 sts=2 sw=2 et:
