parameters:
  - name: environmentName
    type: string

stages:
  - stage: PrivateLinkDNSRecords
    displayName: Set PrivateLink DNS Records
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
      - template: /templates/vars/common.yaml@PipelineCommon
      - template: /templates/vars/regional/northeurope.yaml@PipelineCommon
    jobs:
      - deployment: SetDnsRecords
        displayName: Set DNS Records
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: Resolve Private Endpoint IPs for Container Registry
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(acrName)'

                      - displayName: Set DNS record for Container Registry
                        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: Resolve Private Endpoint IPs for KeyVault
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(keyVaultName)'

                      - displayName: Set DNS record for KeyVault
                        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: Resolve Private Endpoint IPs for Redis
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(redisName)'

                      - displayName: Set DNS record for Redis
                        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: Resolve Private Endpoint IPs for Search
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(searchServiceName)'

                      - displayName: Set DNS record for Search
                        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: Resolve Private Endpoint IPs for SQL Server
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(sqlServerName)'

                      - displayName: Set DNS record for SQL Server
                        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

# vim: set ts=2 sts=2 sw=2 et:
