parameters:
  - name: environmentName
    type: string

stages:
  - stage: PrivateLinkDNSRecords
    displayName: Set Private Endpoint DNS Records
    variables:
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"
      - template: /templates/vars/common.yaml@PipelineCommon
      - template: /templates/vars/regional/northeurope.yaml@PipelineCommon
    jobs:
      - deployment: SetDnsRecords
        displayName: Set DNS Records
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "ACR: Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(acrName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "ACR: Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "KeyVault: Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(keyVaultName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "KeyVault: Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Redis: Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(redisName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Redis: Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(classicServiceConnection)
                    scriptsList:
                      - displayName: "Redis (Classic): Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(classicResourceGroupName)'
                          -ResourceName '$(classicRedisName)'
                          -Subscription '$(classicSubscriptionName)'

                      - displayName: "Redis (Classic): Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Search: Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(searchServiceName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Search: Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(classicServiceConnection)
                    scriptsList:
                      - displayName: "Search (Classic): Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(classicResourceGroupName)'
                          -ResourceName '$(classicSearchServiceName)'
                          -Subscription '$(classicSubscriptionName)'

                      - displayName: "Search (Classic): Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "Storage: Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(storageAccountName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "Storage: Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(serviceConnection)
                    scriptsList:
                      - displayName: "SQL: Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(resourceGroupName)'
                          -ResourceName '$(sqlServerName)'
                          -Subscription '$(subscriptionName)'

                      - displayName: "SQL: Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

                - template: /templates/steps/powershell.yaml@PipelineCommon
                  parameters:
                    azureResourceManagerConnection: AZR-MST-PrivateLinkDNS
                    variables:
                      projectServiceConnection: $(classicServiceConnection)
                    scriptsList:
                      - displayName: "SQL (Classic): Resolve Private Endpoint IPs"
                        serviceConnectionVariableName: projectServiceConnection
                        scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                        scriptArguments: >
                          -ResourceGroupName '$(classicResourceGroupName)'
                          -ResourceName '$(classicSqlServerName)'
                          -Subscription '$(classicSubscriptionName)'

                      - displayName: "SQL (Classic): Set DNS records"
                        condition: and(not(failed()), not(canceled()), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
                        scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                        scriptArguments: >
                          -UpdateAllDnsZones $true

# vim: set ts=2 sts=2 sw=2 et:
