environment: dev
replicas: 3

container:
  image: manicminer/ms-identity-redirect-handler
  imagePullPolicy: Always

secretStore:
  name: "external-secrets-azure-ccoe"

externalSecret:
  enabled: true
  refreshInterval: 1h
  certs:
    - secretKey: ipaffs-tls
      remoteKey: secret/star-azure-defra-cloud-cert

# vim: set ts=2 sts=2 sw=2 et:
