#!/usr/bin/env bash

## generate-validator-notification.sh
##
## Build the Slack payload announcing a configuration validator run
##
## usage $0 [Link to published artefact] [Artefact name] [Environment]
## Required arguments
## [$1] - Published artefact URL
## [$2] - Published artefact name
## [$3] - Environment
set -euo pipefail

ARTIFACT_URL="$1"
ARTIFACT_NAME="$2"
ENVIRONMENT="$3"
OUTPUT_PAYLOAD="slack_payload.json"

cat <<EOF > "$OUTPUT_PAYLOAD"
{
  "attachments": [
    {
      "color": "#36A64F",
      "blocks": [
        {
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": "Configuration Validator Completed for ${ENVIRONMENT}",
            "emoji": true
          }
        },
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "The configuration validator ran for *${ENVIRONMENT}*. The results artefact <${ARTIFACT_URL}|${ARTIFACT_NAME}> is available to download."
          }
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "mrkdwn",
              "text": "Generated by Configuration Validator CI | $(date '+%Y-%m-%d %H:%M:%S %Z')"
            }
          ]
        }
      ]
    }
  ]
}
EOF

echo ":: Slack payload saved to '$OUTPUT_PAYLOAD'."
