#!/bin/bash

set -euo pipefail

: "${SERVICE_NAME:?SERVICE_NAME is required}"
: "${BUILD_NUMBER:?BUILD_NUMBER is required}"
: "${ACR_LOGIN_SERVER:?ACR_LOGIN_SERVER is required}"
: "${MANIFEST_ROOT:?MANIFEST_ROOT is required}"
: "${SERVICE_ROOT:?SERVICE_ROOT is required}"

if ! command -v yq >/dev/null 2>&1; then
  echo "yq is required but was not found on PATH" >&2
  exit 1
fi

ensure_autogenerated_header() {
  local file="$1"
  local header_1="# AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY."
  local header_2="# Source of truth is in the microservice repository."
  local existing_header=""
  local tmp_file=""

  existing_header="$(head -n 2 "${file}" 2>/dev/null || true)"
  if [[ "${existing_header}" == "${header_1}"$'\n'"${header_2}" ]]; then
    return
  fi

  tmp_file="$(mktemp)"
  {
    printf "%s\n" "${header_1}"
    printf "%s\n" "${header_2}"
    cat "${file}"
  } > "${tmp_file}"
  mv "${tmp_file}" "${file}"
}

cd "${MANIFEST_ROOT}"

mkdir -p "services/${SERVICE_NAME}"
base_file="services/${SERVICE_NAME}/base.yaml"

values_source_dir=""
for candidate in "${SERVICE_ROOT}/deployment" "${SERVICE_ROOT}/config"; do
  if [[ -f "${candidate}/values.yaml" ]]; then
    values_source_dir="${candidate}"
    break
  fi
done

if [[ -n "${values_source_dir}" ]]; then
  cp "${values_source_dir}/values.yaml" "${base_file}"
else
  echo "No values.yaml found under ${SERVICE_ROOT}/deployment or ${SERVICE_ROOT}/config, using existing or empty base file"
  if [[ ! -f "${base_file}" ]]; then
    printf "{}\n" > "${base_file}"
  fi
fi

service_image="${ACR_LOGIN_SERVER}/ipaffs/${SERVICE_NAME}:${BUILD_NUMBER}"
migrations_image="${ACR_LOGIN_SERVER}/ipaffs/${SERVICE_NAME}-configuration:${BUILD_NUMBER}"
migrations_enabled_in_base="$(yq e '.database.migrations.enabled // false' "${base_file}" | tr '[:upper:]' '[:lower:]')"

SERVICE_IMAGE="${service_image}" yq -i '
  .container.image = strenv(SERVICE_IMAGE)
' "${base_file}"

if [[ "${migrations_enabled_in_base}" == "true" ]]; then
  MIGRATIONS_IMAGE="${migrations_image}" yq -i '
    .database.migrations.enabled = true |
    .database.migrations.image = strenv(MIGRATIONS_IMAGE)
  ' "${base_file}"
fi

ensure_autogenerated_header "${base_file}"

for environment in dev tst pre prd; do
  env_file="environments/${environment}/${SERVICE_NAME}.yaml"
  mkdir -p "$(dirname "${env_file}")"

  if [[ -n "${values_source_dir}" ]] && [[ -f "${values_source_dir}/${environment}/values.yaml" ]]; then
    cp "${values_source_dir}/${environment}/values.yaml" "${env_file}"
  elif [[ ! -f "${env_file}" ]]; then
    printf "{}\n" > "${env_file}"
  fi

  ensure_autogenerated_header "${env_file}"
done

# vim: set ts=2 sts=2 sw=2 et:
