#!/bin/bash

set -euo pipefail

: "${CHART_VERSION:?CHART_VERSION is required}"
: "${MANIFEST_ROOT:?MANIFEST_ROOT is required}"
: "${INFRA_ROOT:?INFRA_ROOT is required}"

ensure_autogenerated_header() {
  local file="$1"
  local header_1="# AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY."
  local header_2="# Source of truth is DEFRA/ipaffs-infra helm-charts/bootstrap."
  local existing_header=""
  local tmp_file=""

  existing_header="$(head -n 2 "${file}" 2>/dev/null || true)"
  if [[ "${existing_header}" == "${header_1}"$'\n'"${header_2}" ]]; then
    return
  fi

  tmp_file="$(mktemp)"
  {
    printf "%s\n" "${header_1}"
    printf "%s\n" "${header_2}"
    cat "${file}"
  } > "${tmp_file}"
  mv "${tmp_file}" "${file}"
}

copy_or_default() {
  local source_file="$1"
  local destination_file="$2"

  mkdir -p "$(dirname "${destination_file}")"

  if [[ -f "${source_file}" ]]; then
    cp "${source_file}" "${destination_file}"
  else
    printf "{}\n" > "${destination_file}"
  fi

  ensure_autogenerated_header "${destination_file}"
}

update_bootstrap_chart_version() {
  local file="$1"
  local version="$2"
  local tmp_file=""

  tmp_file="$(mktemp)"

  if ! awk -v version="$version" '
    BEGIN {
      in_bootstrap = 0
      updated = 0
    }
    /^  - name: bootstrap$/ {
      in_bootstrap = 1
      print
      next
    }
    in_bootstrap && /^  - name: / {
      in_bootstrap = 0
    }
    in_bootstrap && /^    version:/ {
      print "    version: " version
      updated = 1
      next
    }
    {
      print
    }
    END {
      if (updated == 0) {
        exit 1
      }
    }
  ' "${file}" > "${tmp_file}"; then
    rm -f "${tmp_file}"
    echo "Failed to update bootstrap chart version in ${file}" >&2
    exit 1
  fi

  mv "${tmp_file}" "${file}"
}

bootstrap_chart_root="${INFRA_ROOT}/helm-charts/bootstrap"
bootstrap_env_root="${INFRA_ROOT}/helm-charts/envs"

if [[ ! -f "${bootstrap_chart_root}/values.yaml" ]]; then
  echo "Bootstrap values source file not found: ${bootstrap_chart_root}/values.yaml" >&2
  exit 1
fi

copy_or_default \
  "${bootstrap_chart_root}/values.yaml" \
  "${MANIFEST_ROOT}/bootstrap/values.yaml"

for environment in dev tst pre prd; do
  copy_or_default \
    "${bootstrap_env_root}/${environment}/bootstrap-values.yaml" \
    "${MANIFEST_ROOT}/bootstrap/environments/${environment}.yaml"
done

update_bootstrap_chart_version "${MANIFEST_ROOT}/helmfile.yaml.gotmpl" "${CHART_VERSION}"

# vim: set ts=2 sts=2 sw=2 et:
