---
parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

  - name: serviceName
    type: string

  - name: dockerFile
    type: string
    default: Dockerfile

  - name: migrations
    type: boolean
    default: false


stages:
  - stage: BuildService
    displayName: Build Service
    jobs:
      - template: /pipelines/jobs/build-java-project.yaml@ipaffs-infra

  - stage: PackageService
    displayName: Package Service Image
    dependsOn: BuildService
    jobs:
      - template: /pipelines/jobs/package-java-project.yaml@ipaffs-infra
        parameters:
          migrations: ${{ parameters.migrations }}
          serviceName:  "${{ parameters.serviceName }}"
          dockerFile: "${{ parameters.dockerFile }}"

  - stage: ConfigureDeployment
    displayName: Configure Deployment
    dependsOn:
      - PackageService
    variables:
      - name: branch
        value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
      - name: trunkBranch
        value: master
    jobs:
      - job: SetNamespace
        displayName: Set Namespace
        steps:
          - template: /pipelines/steps/determine-namespace.yaml@ipaffs-infra
            parameters:
              branch: $(branch)
              environmentName: ${{ parameters.environmentName }}
              trunkBranch: $(trunkBranch)

  - stage: DeployIdentities
    displayName: Deploy and configure identity infrastructure
    dependsOn: ConfigureDeployment
    variables:
      - name: namespace
        value: $[stageDependencies.ConfigureDeployment.SetNamespace.outputs['Namespace.namespace']]
    jobs:
      - template: /pipelines/jobs/deploy-identities.yaml@ipaffs-infra
        parameters:
          environmentName: ${{ parameters.environmentName }}
          migrations: ${{ parameters.migrations }}
          namespace: $(namespace)
          serviceName: $(serviceName)

  - stage: DeployChart
    displayName: Deploy Helm Charts
    dependsOn:
      - ConfigureDeployment
      - DeployIdentities
    variables:
      - name: namespace
        value: $[stageDependencies.ConfigureDeployment.SetNamespace.outputs['Namespace.namespace']]
      - name: migrationsClientId
        value: $[stageDependencies.DeployIdentities.MigrationsIdentity.outputs['CreateIdentity.clientId']]
      - name: serviceClientId
        value: $[stageDependencies.DeployIdentities.ServiceIdentity.outputs['CreateIdentity.clientId']]
      - name: servicePrincipalName
        value: $[stageDependencies.DeployIdentities.ServiceIdentity.outputs['CreateIdentity.principalName']]
    jobs:
      - template: /pipelines/jobs/deploy-chart.yaml@ipaffs-infra
        parameters:
          environmentName: ${{ parameters.environmentName }}
          namespace: $(namespace)
          serviceName: $(serviceName)
          serviceVersion: $(Build.BuildNumber)
          migrationsClientId: $(migrationsClientId)
          serviceClientId: $(serviceClientId)
          servicePrincipalName: $(servicePrincipalName)

# vim: set ts=2 sts=2 sw=2 et:
