---
parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV

  - name: mvnGoals
    type: string
    default: verify jacoco:report package

  - name: mavenPomFile
    type: string
    default: 'pom.xml'

  - name: targetPath
    type: string
    default: $(Build.SourcesDirectory)/target

  - name: sonarAnalysis
    type: boolean
    default: false

  - name: sonarReferenceBranch
    type: string
    default: main

stages:
  - stage: BuildLibrary
    displayName: Build Library
    variables:
      - group: Common
      - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
          - group: HigherEnvs
      - ${{ else }}:
          - group: LowerEnvs
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"

    condition: and(
      not(failed()), not(canceled()))
    jobs:
      - template: /pipelines/jobs/build-java-project.yaml@ipaffs-infra
        parameters:
          mvnGoals:  "${{ parameters.mvnGoals }}"
          mavenPomFile:  "${{ parameters.mavenPomFile }}"
          targetPath:  "${{ parameters.targetPath }}"
          publishArtifact: false

  - ${{ if eq(parameters.sonarAnalysis, true) }}:
    - stage: SonarAnalysis
      displayName: SonarQube Analysis
      variables:
        - group: Common
        - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
            - group: HigherEnvs
        - ${{ else }}:
            - group: LowerEnvs
        - group: "${{ parameters.environmentName }}"
        - template: "/pipelines/vars/common.yaml"
        - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"

      dependsOn: BuildLibrary
      condition: and(
        not(canceled()),
        eq(dependencies.BuildLibrary.result, 'Succeeded'))
      jobs:
        - template: /pipelines/jobs/sonar-analyse-java-library.yaml@ipaffs-infra
          parameters:
            referenceBranch: "${{ parameters.sonarReferenceBranch }}"
            mavenPomFile: "${{ parameters.mavenPomFile }}"

  - stage: ReleaseLibrary
    displayName: Release Library
    variables:
      - group: Common
      - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
          - group: HigherEnvs
      - ${{ else }}:
          - group: LowerEnvs
      - group: "${{ parameters.environmentName }}"
      - template: "/pipelines/vars/common.yaml"
      - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"


    condition: and(
      not(failed()), not(canceled()))
    jobs:
      - template: /pipelines/jobs/release-java-project.yaml@ipaffs-infra
