apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  annotations:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ipaffs
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  sa_password: ZG9ja2VyUGFzc3dvcmQxIQ==

---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ipaffs
  ports:
    - port: 1433
      nodePort: 31433
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: ipaffs
  serviceName: database
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: ipaffs
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: database
          image: localhost:30500/import-notification-database:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: sa_password
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: sa_password
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: database-data

