apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-scripts
data:
  graceful-shutdown.sh: |
    #!/bin/bash
    /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SHUTDOWN"

---
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  sa_password: ZG9ja2VyUGFzc3dvcmQxIQ==

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: ipaffs
  serviceName: database
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: ipaffs
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: database
          image: localhost:30500/import-notification-database:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: sa_password
          lifecycle:
            preStop:
              exec:
                command: ["/opt/mssql-scripts/graceful-shutdown.sh"]
          resources:
            requests:
              memory: "2Gi"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
            - name: mssql-scripts
              mountPath: /opt/mssql-scripts

      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: database-data
        - name: mssql-scripts
          configMap:
            name: database-scripts
            defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ipaffs
  ports:
    - port: 1433
      nodePort: 31433
  type: NodePort
