apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - registry.yaml
  - service-bus.yaml
  - serviceaccount.yaml

secretGenerator:
  - name: ipaffs-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=tls/imp.dev.azure.defra.cloud.pem
      - tls.key=tls/imp.dev.azure.defra.cloud-key.pem
