apiVersion: v1
kind: Secret
metadata:
  name: storage-setup
type: Opaque
data:
  account-key: RWJ5OHZkTTAyeE5PY3FGbHFVd0pQTGxtRXRsQ0RYSjFPVXpGVDUwdVNSWjZJRnN1RnEyVVZFckN6NEk2dHEvSzFTWkZQVE90ci9LQkhCZWtzb0dNR3c9PQ==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-setup-scripts
data:
  storage-setup.sh: |
    #!/bin/bash
    set -e -x
    az storage container create --name notificationdocuments --blob-endpoint $AZURE_STORAGE_SERVICE_ENDPOINT
    az storage container create --name tmp-download --blob-endpoint $AZURE_STORAGE_SERVICE_ENDPOINT

---

apiVersion: batch/v1
kind: Job
metadata:
  name: storage-setup
spec:
  template:
    spec:
      containers:
        - name: storage-setup
          image: mcr.microsoft.com/azure-cli:latest
          command: ["/opt/storage-setup-scripts/storage-setup.sh"]
          volumeMounts:
            - name: storage-setup-scripts
              mountPath: /opt/storage-setup-scripts
          env:
            - name: AZURE_STORAGE_SERVICE_ENDPOINT
              value: http://storage:10000/devstoreaccount1
            - name: AZURE_STORAGE_ACCOUNT
              value: devstoreaccount1
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-setup
                  key: account-key
      volumes:
        - name: storage-setup-scripts
          configMap:
            name: storage-setup-scripts
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4


