apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: storage
      app.kubernetes.io/part-of: ipaffs
  serviceName: storage
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/component: storage
        app.kubernetes.io/part-of: ipaffs
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: storage
          image: mcr.microsoft.com/azure-storage/azurite:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: blob
              containerPort: 10000
            - name: queue
              containerPort: 10001
            - name: table
              containerPort: 10002
          resources:
            requests:
              memory: "1Gi"
          volumeMounts:
            - name: storage-data
              mountPath: /data

      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: storage-data

---
apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  selector:
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ipaffs
  ports:
    - name: blob
      port: 10000
      nodePort: 31000
    - name: queue
      port: 10001
      nodePort: 31001
    - name: table
      port: 10002
      nodePort: 31002
  type: NodePort
