service: ""
project: ipaffs
environment: dev

externalSecret:
  enabled: false

serviceBus:
  enabled: false

azure:
  clientId: ""
  managedIdentityName: ""

schedule: ""
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1
suspend: false

keda:
  enabled: false
  pollingInterval: 30
  cooldownPeriod: 300
  maxReplicaCount: 10
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers: []

container:
  image: ""
  imagePullPolicy: Always
  command: ""
  args: []

initContainer:
  enabled: false

env: []

resources: {}

# vim: set ts=2 sts=2 sw=2 et:
