service: ""
project: ipaffs
environment: dev
imageRegistry: ""

deployment:
  manifestTag: ""

externalSecret:
  enabled: false

serviceBus:
  enabled: false

azure:
  clientId: ""
  managedIdentityName: ""

schedule: ""
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1
suspend: false

keda:
  enabled: false
  pollingInterval: 30
  cooldownPeriod: 300
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers: []

container:
  image: ""
  imagePullPolicy: Always
  command: ""
  args: []
  securityContext:
    allowPrivilegeEscalation: false

initContainer:
  enabled: false
  securityContext:
    allowPrivilegeEscalation: false

env: []

resources: {}

