apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.service }}
  labels:
    {{- include "ipaffs-common.labels" . | nindent 4 }}
spec:
  schedule: {{ required "CronJob schedule is required" .Values.schedule | quote }}
  concurrencyPolicy: {{ default "Forbid" .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ default 3 .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 1 .Values.failedJobsHistoryLimit }}
  suspend: {{ default false .Values.suspend }}
  jobTemplate:
    spec:
      backoffLimit: 2  # max pod retries for each run
      template:
        metadata:
          labels:
            {{- include "ipaffs-common.labels" . | nindent 12 }}
          annotations:
            azure.workload.identity/use: "true"
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.container.image }}"
              {{ if .Values.container.command }}
              command: ["{{ .Values.container.command }}"]
              {{ end }}
              {{ if .Values.container.args }}
              args:
                {{ range .Values.container.args }}
                - "{{ . }}"
                {{ end }}
              {{ end }}
              imagePullPolicy: {{ .Values.container.imagePullPolicy }}
              envFrom:
                - configMapRef:
                    name: ipaffs-config
{{- if .Values.externalSecret.enabled }}
                - secretRef:
                    name: {{ printf "%s-secrets" .Values.service }}
{{- end }}
{{- if .Values.serviceBus.enabled }}
                - secretRef:
                    name: {{ printf "%s-servicebus" .Values.service }}
{{- end }}
              {{ with .Values.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{ end }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
{{- if .Values.initContainer.enabled }}
          initContainers:
            - name: {{ .Chart.Name }}-init
              image: "{{ .Values.initContainer.image }}"
              command: {{ .Values.initContainer.command }}
{{- end }}

# vim: set ts=2 sts=2 sw=2 et:
