---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/**/database-watcher*.json
      - pipelines/database-watcher.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/**/database-watcher*.json
      - pipelines/database-watcher.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

parameters:
  - name: environmentName
    type: string
    default: POC
    values:
      - POC
      - TST
  - name: bicepFiles
    type: stringList
    values:
      - database-watcher
    default:
      - database-watcher

stages:
  - stage: Deploy
    jobs:
      - deployment: DeployBicep
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  name: PrepareResourceGroups
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az group create \
                        --name $(resourceGroupName) \
                        --location $(location)

                - ${{ each template in parameters.bicepFiles }}:
                  - task: AzureCLI@2
                    displayName: WhatIf_${{ template }}
                    inputs:
                      azureSubscription: $(serviceConnection)
                      scriptType: bash
                      scriptLocation: inlineScript
                      inlineScript: |
                        az deployment group what-if \
                          --name "${{ template }}-$(Build.BuildId)" \
                          --resource-group $(resourceGroupName) \
                          --template-file bicep/${{ template }}.bicep \
                          --parameters @bicep/envs/${{ lower(parameters.environmentName) }}/${{ template }}.parameters.json

                  - task: AzureCLI@2
                    displayName: Deploy_${{ template }}
                    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                    inputs:
                      azureSubscription: $(serviceConnection)
                      scriptType: bash
                      scriptLocation: inlineScript
                      inlineScript: |
                        az deployment group create \
                          --name "${{ template }}-$(Build.BuildId)" \
                          --resource-group $(resourceGroupName) \
                          --template-file bicep/${{ template }}.bicep \
                          --parameters @bicep/envs/${{ lower(parameters.environmentName) }}/${{ template }}.parameters.json

# vim: set ts=2 sts=2 sw=2 et:
