---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/**/*.bicepparam
      - bicep/**/*.bicep
      - pipelines/deploy-bicep.yaml
      - pipelines/stages/deploy-bicep-*.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/**/*.bicepparam
      - bicep/**/*.bicep
      - pipelines/deploy-bicep.yaml
      - pipelines/stages/deploy-bicep-*.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV
      - TST
      - PRE
      - PRD
  - name: establishPeering
    displayName: Establish Peering To Hub
    type: boolean
    default: false

variables:
  - group: Common
  - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
    - group: HigherEnvs
  - ${{ else }}:
    - group: LowerEnvs
  - group: "${{ parameters.environmentName }}"
  - template: "/pipelines/vars/common.yaml"
  - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"

stages:
  - stage: TagBuild
    displayName: Tag Build
    jobs:
      - job: TagBuild
        displayName: Tag build
        pool: server
        steps:
          - task: InvokeRESTAPI@1
            inputs:
              serviceConnection: ADO-Generic-defragovuk
              method: PUT
              headers: >
                {"Content-Type": "application/json", "Authorization": "Bearer $(System.AccessToken)"}
              urlSuffix: "/DEFRA-EUTD-IPAFFS/_apis/build/builds/$(Build.BuildId)/tags/Environment-${{ parameters.environmentName }}?api-version=6.0"

  - template: stages/deploy-bicep-resource-group.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-network.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - ${{ if parameters.establishPeering }}:
    - template: stages/establish-peering.yaml
      parameters:
        environmentName: ${{ parameters.environmentName }}

  - ${{ if or(eq(parameters.environmentName, 'DEV'), eq(parameters.environmentName, 'PRD')) }}:
    - template: stages/deploy-bicep-acr.yaml
      parameters:
        environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-classic.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}
      ${{ if eq(parameters.environmentName, 'DEV') }}:
        classicEnvironmentName: SND
      ${{ else }}:
        classicEnvironmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-classic-network.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}
      ${{ if eq(parameters.environmentName, 'DEV') }}:
        classicEnvironmentName: SND
      ${{ else }}:
        classicEnvironmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-infra.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-privatelink.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

# vim: set ts=2 sts=2 sw=2 et:
