---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/10-resource-group.bicep
      - bicep/20-network.bicep
      - bicep/30-infra.bicep
      - bicep/modules/*.bicep
      - bicep/**/30-infra.bicepparam
      - bicep/**/10-10-resource-group.bicepparam
      - pipelines/deploy-bicep.yaml
      - pipelines/stages/deploy-bicep.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/10-resource-group.bicep
      - bicep/20-network.bicep
      - bicep/30-infra.bicep
      - bicep/modules/*.bicep
      - bicep/**/30-infra.bicepparam
      - bicep/**/10-10-resource-group.bicepparam
      - pipelines/deploy-bicep.yaml
      - pipelines/stages/deploy-bicep.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV
      - TST

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

stages:
  - template: stages/deploy-bicep.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

# vim: set ts=2 sts=2 sw=2 et:
