---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/**/*.bicepparam
      - bicep/**/*.bicep
      - pipelines/deploy-bicep.yaml
      - pipelines/stages/deploy-bicep-*.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/**/*.bicepparam
      - bicep/**/*.bicep
      - pipelines/deploy-bicep.yaml
      - pipelines/stages/deploy-bicep-*.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV
      - TST
      - PRE
      - PRD
  - name: establishPeering
    displayName: Establish Peering To Hub
    type: boolean
    default: false

variables:
  - group: Common
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

stages:
  - template: stages/deploy-bicep-resource-group.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-network.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - ${{ if parameters.establishPeering }}:
    - template: stages/establish-peering.yaml
      parameters:
        environmentName: ${{ parameters.environmentName }}

  - ${{ if or(eq(parameters.environmentName, 'DEV'), eq(parameters.environmentName, 'PRD')) }}:
    - template: stages/deploy-bicep-acr.yaml
      parameters:
        environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-classic.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}
      ${{ if eq(parameters.environmentName, 'DEV') }}:
        classicEnvironmentName: SND
      ${{ else }}:
        classicEnvironmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-classic-network.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}
      ${{ if eq(parameters.environmentName, 'DEV') }}:
        classicEnvironmentName: SND
      ${{ else }}:
        classicEnvironmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-infra.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-privatelink.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

# vim: set ts=2 sts=2 sw=2 et:
