---
trigger: none

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

  - name: namespace
    displayName: Namespace
    type: string
    default: foo

  - name: branch
    displayName: Branch Name
    type: string
    default: feature/foo

  - name: services
    displayName: Services
    type: object
    default:
      - name: archive-notifications
        migrations: false
        pipeline: archive-notifications-service
      - name: auto-clearance
        migrations: false
        pipeline: auto-clearance-service
      - name: bcpadmin
        migrations: false
        pipeline: bcpadmin-frontend
      - name: decision
        migrations: true
        pipeline: decision-service
      - name: proxy
        migrations: false
        pipeline: imports-proxy

resources:
  repositories:
    - repository: ipaffs-infra
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-infra
      ref: refs/heads/main

    - repository: archive-notifications
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-archive-notifications-microservice
      ref: refs/heads/feature/IMTA-19940-ado-pipeline

    - repository: auto-clearance
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-auto-clearance-microservice
      ref: refs/heads/master

    - repository: decision
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-decision-microservice
      ref: refs/heads/IMTA-19931-deploy-on-kubernetes-decision-service

    - repository: bcpadmin
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-frontend-bcpadmin
      ref: refs/heads/master

    - repository: proxy
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-imports-proxy
      ref: refs/heads/feature/login-muxer

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
  - name: serviceName
    value: "{{ replace(parameters.serviceName, '-', '_') }}"

stages:
  - stage: ConfigureDeployment
    displayName: Configure Deployment
    jobs:
      - job: DeployBootstrapChart
        displayName: Deploy bootstrap Helm chart
        steps:
          - template: /pipelines/steps/deploy-bootstrap-chart.yaml
            parameters:
              environmentName: ${{ parameters.environmentName }}
              namespace: ${{ parameters.namespace }}

  - ${{ each service in parameters.services }}:
    - stage: DeployIdentities_$(serviceName)
      displayName: Deploy identities for $(serviceName)
        - ConfigureDeployment
      jobs:
        - template: /pipelines/jobs/deploy-identities.yaml
          parameters:
            environmentName: ${{ parameters.environmentName }}
            migrations: ${{ service.migrations }}
            namespace: ${{ parameters.namespace }}
            serviceName: $(serviceName)

  - ${{ each service in parameters.services }}:
      - stage: Metadata_$(serviceName)
        displayName: Metadata for $(serviceName)
        jobs:
          - job: Metadata
            displayName: Get metadata
            variables:
              - name: trunkBranch
                value: $[resources.repositories['$(serviceName)'].ref]
            steps:
              - task: AzureCLI@2
                name: serviceDetails
                displayName: Latest version for $(serviceName)
                env:
                  PIPELINE: ${{ service.pipeline }}
                  BRANCH: $(trunkBranch)
                inputs:
                  azureSubscription: $(serviceConnection)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    set -ex
                    pipelineId="$(az pipelines show --org https://dev.azure.com/defragovuk/ --project DEFRA-EUTD-IPAFFS --folder-path Services --name "${PIPELINE}" --query 'id')"
                    latestBuildId="$(az pipelines runs list --org https://dev.azure.com/defragovuk/ --project DEFRA-EUTD-IPAFFS --query-order FinishTimeDesc --result succeeded --status completed --pipeline-ids "${pipelineId}" --branch "${BRANCH}")"
                    echo "##vso[task.setvariable variable=version;isOutput=true]${latestBuildId}"

  - ${{ each service in parameters.services }}:
    - stage: DeployChart_$(serviceName)
      displayName: Deploy Helm Charts for $(serviceName)
      dependsOn:
        - DeployIdentities_$(serviceName)
        - Metadata_$(serviceName)
      variables:
        - name: migrationsClientId
          value: $[stageDependencies['DeployIdentities_$(serviceName)'].MigrationsIdentity.outputs['CreateIdentity.clientId']]
        - name: serviceClientId
          value: $[stageDependencies['DeployIdentities_$(serviceName)'].ServiceIdentity.outputs['CreateIdentity.clientId']]
        - name: servicePrincipalName
          value: $[stageDependencies['DeployIdentities_$(serviceName)'].ServiceIdentity.outputs['CreateIdentity.principalName']]
        - name: serviceVersion
          value: $[stageDependencies['Metadata_$(serviceName)'].Metadata.outputs['serviceDetails.version']]
      jobs:
        - template: /pipelines/jobs/deploy-chart.yaml
          parameters:
            environmentName: ${{ parameters.environmentName }}
            migrationsClientId: $(migrationsClientId)
            namespace: ${{ parameters.namespace }}
            repository: $(serviceName)
            serviceClientId: $(serviceClientId)
            servicePrincipalName: $(servicePrincipalName)
            serviceName: $(serviceName)
            serviceVersion: $(serviceVersion)

# vim: set ts=2 sts=2 sw=2 et:
