---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/envs/*/10-resource-group.bicepparam
      - bicep/envs/*/20-network.bicepparam
      - bicep/envs/*/30-infra.bicepparam
      - bicep/envs/*/40-privatelink.bicepparam
      - bicep/modules/*.bicep
      - bicep/10-resource-group.bicep
      - bicep/20-network.bicep
      - bicep/30-infra.bicep
      - bicep/40-privatelink.bicep
      - pipelines/deploy-bicep.yaml
      - pipelines/stages/deploy-bicep-resource-group.yaml
      - pipelines/stages/deploy-bicep-network.yaml
      - pipelines/stages/deploy-bicep-infra.yaml
      - pipelines/stages/deploy-bicep-privatelink.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/envs/*/10-resource-group.bicepparam
      - bicep/envs/*/20-network.bicepparam
      - bicep/envs/*/30-infra.bicepparam
      - bicep/envs/*/40-privatelink.bicepparam
      - bicep/modules/*.bicep
      - bicep/10-resource-group.bicep
      - bicep/20-network.bicep
      - bicep/30-infra.bicep
      - bicep/40-privatelink.bicep
      - pipelines/deploy-bicep.yaml
      - pipelines/stages/deploy-bicep-resource-group.yaml
      - pipelines/stages/deploy-bicep-network.yaml
      - pipelines/stages/deploy-bicep-infra.yaml
      - pipelines/stages/deploy-bicep-privatelink.yaml

pool:
  name: DEFRA-COMMON-UBUNTU-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV
      - TST

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

stages:
  - template: stages/deploy-bicep-resource-group.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-network.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-infra.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-privatelink.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

# vim: set ts=2 sts=2 sw=2 et:
