---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/entra-groups.yaml
      - pipelines/stages/entra-groups.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/entra-groups.yaml
      - pipelines/stages/entra-groups.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v6-latest

stages:
  - template: stages/entra-groups.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

# vim: set ts=2 sts=2 sw=2 et:
