---
pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC
  - name: serviceName
    displayName: ServiceName
    type: string

stages:
  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure
    jobs:
      - job:
        variables:
          - group: "${{ parameters.environmentName }}"
          - name: lowerResourceGroupName
            value: $[lower(variables.resourceGroupName)]
        steps:
          - task: AzureCLI@2
            env:
              MANAGED_IDENTITY_NAME: $(lowerResourceGroupName)-migrations-${{ parameters.serviceName }}-ipaffs-test
              AKS_MIGRATION_CREDENTIAL: ${{ parameters.serviceName }}-migration
              AKS_MIGRATION_ISSUER: $(aksMigrationIssuer)
              AKS_MIGRATION_AUDIENCES: $(aksMigrationAudiences)
              AKS_MIGRATION_SUBJECT: $(aksMigrationSubject)
        inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail
                set -x                            
                            
                # Create Managed Identity and Federated Credential
                az identity create --name "${MANAGED_IDENTITY_NAME}" --resource-group $(lowerResourceGroupName)
                az identity federated-credential create --identity-name "${MANAGED_IDENTITY_NAME}" --resource-group $(lowerResourceGroupName) --name "${AKS_MIGRATION_CREDENTIAL}" --issuer "${AKS_MIGRATION_ISSUER}" --audiences "${AKS_MIGRATION_AUDIENCES}" --subject "${AKS_MIGRATION_SUBJECT}"
                
                # Add Managed Identity to SQL Admin Group
                RESULT="$(az ad group member add -g $(sqlAdminGroupId) --member-id 4b2fbef7-de9d-4836-a44e-46c56aad3d9e 2>&1)"
                if [[ "$RESULT" =~ "One or more added object references already exist" ]]; then exit 0; fi
                exit 1
# vim: set ts=2 sts=2 sw=2 et:
