---
pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

stages:
  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure
    jobs:
      - job:
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                RESULT="$(az ad group member add -g 65c89463-4af9-4520-bc82-77f0ead4e424 --member-id 4b2fbef7-de9d-4836-a44e-46c56aad3d9e)"
                if [[ "$RESULT" =~ "One or more added object references already exist" ]; then exit 0; fi
                exit 1

# vim: set ts=2 sts=2 sw=2 et:
