---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/import-acr-artifacts.yaml
      - pipelines/steps/import-container-images.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/import-acr-artifacts.yaml
      - pipelines/steps/import-container-images.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

stages:
  - stage: ImportACRArtifacts
    displayName: Import ACR Artifacts
    jobs:
      - deployment: ImportContainerImages
        displayName: Import Container Images
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: steps/import-container-images.yaml

# vim: set ts=2 sts=2 sw=2 et:
