---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/import-acr-artifacts.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/import-acr-artifacts.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

parameters:
  - name: environmentName
    type: string
    default: POC
    values:
      - POC
  - name: imagesToImport
    type: object
    default:
      - displayName: ingress-nginx
        source: registry.k8s.io/ingress-nginx/controller:v1.13.3
        image: ingress-nginx/controller:v1.13.3

stages:
  - stage: Deploy
    jobs:
      - deployment: DeployBicep
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - ${{ each image in parameters.imagesToImport }}:
                  - task: AzureCLI@2
                    name: ImportImage_${{ image.displayName }}
                    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                    inputs:
                      azureSubscription: $(serviceConnection)
                      scriptType: bash
                      scriptLocation: inlineScript
                      inlineScript: |
                        az acr import \
                          --name $(acrName) \
                          --source ${{ image.source }} \
                          --image ${{ image.image }}

# vim: set ts=2 sts=2 sw=2 et:
