---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/infra-permissions.yaml
      - pipelines/stages/infra-permissions.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/infra-permissions.yaml
      - pipelines/stages/infra-permissions.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

stages:
  - template: stages/infra-permissions.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

# vim: set ts=2 sts=2 sw=2 et:
