---
trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

pool:
  name: DEFRA-COMMON-UBUNTU-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV
      - TST

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
  - name: helmDryRun
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      value: ''
    ${{ else }}:
      value: '--dry-run'

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v6-latest

stages:
  - template: stages/entra-groups.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-resource-group.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-network.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-infra.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/infra-permissions.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/import-acr-artifacts.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/install-helm-charts.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/deploy-bicep-privatelink.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

  - template: stages/private-endpoint-dns-records.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

# vim: set ts=2 sts=2 sw=2 et:
