---
pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
  - name: ssvServiceConnection
    value: 'AZR-SSV5-IPAFFS'
  - name: helmDryRun
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      value: ''
    ${{ else }}:
      value: '--dry-run'

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v6-latest

stages:

  - stage: create_aad_groups
    displayName: Create AAD Groups
    jobs:
      - deployment: CreateAADGroups
        displayName: Create AAD Groups
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzurePowerShell@5
                  displayName: Run Create-AADGroups script
                  inputs:
                    azureSubscription: 'AZR-SSV5-IPAFFS'
                    ScriptType: 'FilePath'
                    ScriptPath: 'scripts/pipeline/Create-AADGroups.ps1'
                    ScriptArguments: >
                      -AADGroupsJsonManifestPath 'pipelines/vars/entra/aad-group.json'
                    azurePowerShellVersion: 'LatestVersion'
                    pwsh: true
                    addSpnToEnvironment: true
