---
pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
  - name: helmDryRun
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      value: ''
    ${{ else }}:
      value: '--dry-run'

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v6-latest

stages:
  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure
    jobs:
      - deployment: DeployBicep
        displayName: Deploy Bicep Templates
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: steps/deploy-bicep.yaml
                  parameters:
                    environmentName: "${{ parameters.environmentName }}"
  
  - stage: DNS
    displayName: DNS
    jobs:
      - deployment: DNS
        displayName: DNS
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: PipelineCommon
                      
                - task: Bash@3
                  displayName: "Set PrivateEndpointDnsRecordsJson variable"
                  inputs:
                    targetType: 'inline'
                    script: |
                      privateEndpointDnsRecordString='[{"Region":"uksouth","Fqdn":"pocimpinfak1401-40umdsag.hcp.uksouth.azmk8s.io","IpAddress":"10.179.104.191"}]'
                
                      echo "privateEndpointDnsRecordString: $privateEndpointDnsRecordString"
                
                      # Set Azure DevOps pipeline variable
                      echo "##vso[task.setvariable variable=PrivateEndpointDnsRecordsJson]$privateEndpointDnsRecordString"
              
                - task: AzurePowerShell@5
                  displayName: 'Set DNS record'
                  inputs:
                    azureSubscription: AZR-MST-PrivateLinkDNS
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: './PowerShellLibrary/Set-PrivateDnsRecordSet.ps1'
                    ScriptArguments: '-UpdateAllDnsZones $true'
                    pwsh: true
                    
  - stage: ImportAcrArtifacts
    displayName: Import ACR Artifacts
    jobs:
      - deployment: ImportContainerImages
        displayName: Import Container Images
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: steps/import-container-images.yaml

  - stage: DeployHelmCharts
    displayName: Deploy Helm Charts
    jobs:
      - deployment: DeployHelm
        displayName: Deploy with Helm
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: steps/install-helm-charts.yaml

# vim: set ts=2 sts=2 sw=2 et:
