trigger:
  branches:
    include:
      - main

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  azureSubscription: 'ADO-DefraGovUK-AZR-POC_IMP' # Name of service connection
  resourceGroupName: 'POCIMPNETNS1401'
  location: 'UKSouth'

parameters:
- name: network
  type: object
  default:
    - virtual-network
    - network-security-group
- name: infra
  type: object
  default:
    - acr
    - aks-cluster
- name: charts
  type: object
  default:
    - name: ingress-nginx
      release: ingress-nginx
      chartName: ingress-nginx
      repoUrl: https://kubernetes.github.io/ingress-nginx
      namespace: ingress-nginx
      valuesFile: helm-charts/ingress-nginx-values.yaml

stages:
  - stage: DeployBaseInfrastructure
    jobs:
      - job: Deploy
        steps:
          - task: AzureCLI@2
            name: PrepareResourceGroups
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group create \
                  --name $(resourceGroupName) \
                  --location $(location)

          - ${{ each template in parameters.network }}:
            - task: AzureCLI@2
              displayName: Deploy_${{ template }}
              condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
              inputs:
                azureSubscription: $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az deployment group create \
                    --name "${{ replace(template, '.bicep', '') }}-$(Build.BuildId)" \
                    --resource-group $(resourceGroupName) \
                    --template-file bicep/${{ template }}.bicep \
                    --parameters @bicep/envs/poc/${{ template }}.parameters.json
          
          - ${{ each template in parameters.infra }}:
            - task: AzureCLI@2
              displayName: Deploy_${{ template }}
              condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
              inputs:
                azureSubscription: $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az deployment group create \
                    --name "${{ replace(template, '.bicep', '') }}-$(Build.BuildId)" \
                    --resource-group $(resourceGroupName) \
                    --template-file bicep/${{ template }}.bicep \
                    --parameters @bicep/envs/poc/${{ template }}.parameters.json

          - ${{ each c in parameters.charts }}:
              - task: HelmDeploy@0
                displayName: "Helm Install ${{ c.release }}"
                inputs:
                  connectionType: 'Azure Resource Manager'
                  azureSubscription: $(azureSubscription)
                  azureResourceGroup: $(resourceGroupName)
                  kubernetesCluster: POCIMPINFAK1401
                  namespace: ${{ c.namespace }}
                  command: 'upgrade'
                  chartName: ${{ c.chartName }}
                  releaseName: ${{ c.release }}
                  install: true
                  useClusterAdmin: true
                  arguments: >-
                    --repo https://kubernetes.github.io/ingress-nginx
                    -f ${{ c.valuesFile }}
                    --create-namespace  