---
pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
  - name: helmDryRun
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      value: ''
    ${{ else }}:
      value: '--dry-run'

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v6-latest

stages:
  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure
    jobs:
      - deployment: DeployBicep
        displayName: Deploy Bicep Templates
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: steps/deploy-bicep.yaml
                  parameters:
                    environmentName: "${{ parameters.environmentName }}"
  
  - stage: DNS
    displayName: DNS
    jobs:
      - deployment: DNS
        displayName: DNS
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:              
                - task: AzureCLI@2
                  displayName: "Create/Update Private DNS A Record"
                  inputs:
                    scriptType: bash
                    azureSubscription: AZR-MST-PrivateLinkDNS
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az network private-dns record-set a add-record --resource-group mstinfdnsrgp001 --zone-name northeurope.azmk8s.io --record-set-name pocimpinfak1401-40umdsag.hcp --ipv4-address 10.179.104.191
                      az network private-dns record-set a add-record --resource-group mstinfdnsrgp201 --zone-name westeurope.azmk8s.io --record-set-name pocimpinfak1401-40umdsag.hcp --ipv4-address 10.179.104.191
                      az network private-dns record-set a add-record --resource-group mstinfdnsrgp401 --zone-name uksouth.azmk8s.io --record-set-name pocimpinfak1401-40umdsag.hcp --ipv4-address 10.179.104.191
                      az network private-dns record-set a add-record --resource-group mstinfdnsrgp601 --zone-name ukwest.azmk8s.io --record-set-name pocimpinfak1401-40umdsag.hcp --ipv4-address 10.179.104.191
                    
  - stage: ImportAcrArtifacts
    displayName: Import ACR Artifacts
    jobs:
      - deployment: ImportContainerImages
        displayName: Import Container Images
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: steps/import-container-images.yaml

  - stage: DeployHelmCharts
    displayName: Deploy Helm Charts
    jobs:
      - deployment: DeployHelm
        displayName: Deploy with Helm
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: steps/install-helm-charts.yaml

# vim: set ts=2 sts=2 sw=2 et:
