---
pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
  - name: ssvServiceConnection
    value: 'AZR-SSV5-IPAFFS'
  - name: helmDryRun
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      value: ''
    ${{ else }}:
      value: '--dry-run'

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v6-latest

stages:
  # - stage: DeployInfrastructure
  #   displayName: Deploy Infrastructure
  #   jobs:
  #     - deployment: DeployBicep
  #       displayName: Deploy Bicep Templates
  #       environment:
  #         name: "${{ parameters.environmentName }}"
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - checkout: self
  #               - template: steps/deploy-bicep.yaml
  #                 parameters:
  #                   environmentName: "${{ parameters.environmentName }}"

  # - template: /pipelines/stages/privatelink-dns-records.yaml
  #   parameters:
  #     environmentName: ${{ parameters.environmentName }}

  # - stage: ImportAcrArtifacts
  #   displayName: Import ACR Artifacts
  #   jobs:
  #     - deployment: ImportContainerImages
  #       displayName: Import Container Images
  #       condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  #       environment:
  #         name: "${{ parameters.environmentName }}"
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - checkout: self
  #               - template: steps/import-container-images.yaml


  - stage: create_aad_groups
    displayName: Create AAD Groups
    jobs:
      - deployment: CreateAADGroups
        displayName: Create AAD Groups
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzurePowerShell@5
                  displayName: Run Create-AADGroups script
                  inputs:
                    azureSubscription: $(ssvServiceConnection)
                    ScriptType: 'FilePath'
                    ScriptPath: 'scripts/pipeline/Create-AADGroups.ps1'
                    ScriptArguments: >
                      -AADGroupsJsonManifestPath 'pipelines/vars/entra/aad-group.json'
                    azurePowerShellVersion: 'LatestVersion'
                    pwsh: true

  # - stage: DeployHelmCharts
  #   displayName: Deploy Helm Charts
  #   jobs:
  #     - deployment: DeployHelm
  #       displayName: Deploy with Helm
  #       environment:
  #         name: "${{ parameters.environmentName }}"
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - checkout: self
  #               - template: steps/install-helm-charts.yaml

# vim: set ts=2 sts=2 sw=2 et:
