---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - helm-charts/*-values.yaml
      - pipelines/install-helm-charts.yaml
      - pipelines/steps/install-helm-charts.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - helm-charts/*-values.yaml
      - pipelines/install-helm-charts.yaml
      - pipelines/steps/install-helm-charts.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
  - name: helmDryRun
    value: ''

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: POC
    values:
      - POC

stages:
  - stage: InstallHelmCharts
    displayName: Install Helm Charts
    jobs:
      - deployment: InstallHelmCharts
        displayName: Install Charts
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: steps/install-helm-charts.yaml

# vim: set ts=2 sts=2 sw=2 et:
