---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - helm-charts/*-values.yaml
      - pipelines/install-helm-charts.yaml
      - pipelines/stages/install-helm-charts.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - helm-charts/*-values.yaml
      - pipelines/install-helm-charts.yaml
      - pipelines/stages/install-helm-charts.yaml

pool:
  name: DEFRA-COMMON-UBUNTU-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV
      - TST

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"
  - name: helmDryRun
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      value: ''
    ${{ else }}:
      value: '--dry-run'

stages:
  - template: stages/install-helm-charts.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}

# vim: set ts=2 sts=2 sw=2 et:
