trigger:
  branches:
    include:
      - main
  paths:
      include:
        - helm-charts/ipaffs-backend/*

pool:
  name: 'DEFRA-COMMON-ubuntu2204-SSV5'

variables:
  azureSubscription: 'ADO-DefraGovUK-AZR-POC_IMP'
  acrName: 'pocimpinfac1401'
  helmChartPath: './helm-charts/ipaffs-backend'
  helmChartName: 'ipaffs-backend'
  helmChartVersion: '0.1.0'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Logging in to ACR."
        az acr login --name $(acrName)
        
        echo "Packaging Helm Chart."
        helm dependency update  $(helmChartPath)
        helm package $(helmChartPath) --version $(helmChartVersion)

        echo "Pushing Helm chart to ACR..."
        helm push $(helmChartName)-$(helmChartVersion).tgz oci://$(acrName).azurecr.io/helm/v1/repo
