trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - helm-charts/ipaffs-common/**
      - pipelines/ipaffs-common-chart.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - helm-charts/ipaffs-common/**
      - pipelines/ipaffs-common-chart.yaml

pool:
  name: 'DEFRA-COMMON-ubuntu2204-SSV5'

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

stages:
  - template: stages/package-helm-chart.yaml
    parameters:
      helmChartName: ipaffs-common
      helmChartPath: helm-charts/ipaffs-common

# vim: set ts=2 sts=2 sw=2 et:
