---
trigger:
  branches:
    include:
      - imta-21564-drift

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: Common
  - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
      - group: HigherEnvs
  - ${{ else }}:
      - group: LowerEnvs
  - group: "${{ parameters.environmentName }}"
  - template: "/pipelines/vars/common.yaml"
  - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"

parameters:
  - name: environmentName
    type: string
    default: PRE
    values:
      - PRE

stages:
  - stage: Deploy
    jobs:
      - deployment: Deploy
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: Deploy
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az account show
                      rsync -av "${AZURE_CONFIG_DIR}"/ "$(Pipeline.Workspace)/.azure/"

                - task: AzureCLI@2
                  displayName: Deploy
                  inputs:
                    azureSubscription: $(classicServiceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az account show
                      rsync -av "${AZURE_CONFIG_DIR}"/ "$(Pipeline.Workspace)/.azure2/"

                - task: AzureCLI@2
                  displayName: Deploy
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      cat >my-config-file <<EOF
                      SOURCE_VAULT_NAME=$(keyVaultName)
                      SOURCE_VAULT_AZCLI_DIR=$(Pipeline.Workspace)/.azure
                      TARGET_VAULT_NAME=$(classicKeyVaultName)
                      TARGET_VAULT_AZCLI_DIR=$(Pipeline.Workspace)/.azure2
                      APP_SERVICE_SUBSCRIPTION=$(classicSubscriptionName)
                      ENVIRONMENT=${{ lower(parameters.environmentName) }}
                      SERVICES_DIR=../../../../ipaffs-manifest/services
                      ENVIRONMENTS_DIR=../../../../ipaffs-manifest/environments
                      SERVICE_MAPPING_FILE=./service-mapping-tst.txt
                      EOF

                      # scripts/pipeline/configuration-validator/validator.sh ... my-config-file

# vim: set ts=2 sts=2 sw=2 et:
