---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/legacy.bicep
      - bicep/**/legacy.bicepparam
      - pipelines/legacy.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/legacy.bicep
      - bicep/**/legacy.bicepparam
      - pipelines/legacy.yaml

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: SND
    values:
      - SND
      - TST
      - PRE
      - PRD

stages:
  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure
    jobs:
      - deployment: DeployBicep
        displayName: Deploy Bicep Templates
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: WhatIf - Legacy
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az deployment group what-if \
                        --name "Legacy-$(Build.BuildId)" \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/legacy.bicep \
                        --parameters bicep/envs/${{ lower(parameters.environmentName) }}/legacy.bicepparam

                - task: AzureCLI@2
                  displayName: Deploy - Legacy
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az deployment group create \
                        --name "Legacy-$(Build.BuildId)" \
                        --resource-group $(resourceGroupName) \
                        --template-file bicep/legacy.bicep \
                        --parameters bicep/envs/${{ lower(parameters.environmentName) }}/legacy.bicepparam

# vim: set ts=2 sts=2 sw=2 et:
