---
trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV

variables:
  - group: "${{ parameters.environmentName }}"
  - template: "vars/common.yaml"
  - template: "vars/${{ lower(parameters.environmentName) }}.yaml"

stages:
  - stage: EstabishHubPeering
    displayName: Establish Hub Peering
    jobs:
      - deployment: TriggerPeeringPipeline
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: Bash@3
                  env:
                    ADO_ORG_URL: $(System.CollectionUri)
                    ADO_PROJECT: $(System.TeamProject)
                    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
                    SUBSCRIPTION_NAME: $(subscriptionName)
                    TENANT_ID: $(tenantId)
                    VNET_NAME: $(vnetName)
                  inputs:
                    filePath: scripts/pipeline/trigger-peering-pipeline.sh

# vim: set ts=2 sts=2 sw=2 et:
