---
trigger: none
pr: none

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV
      - TST
      - PRE
      - PRD

  - name: imageTag
    displayName: Image Tag
    type: string
    default: latest

variables:
  - group: Common
  - ${{ if or(eq(parameters.environmentName, 'PRD'), eq(parameters.environmentName, 'PRE')) }}:
      - group: HigherEnvs
  - ${{ else }}:
      - group: LowerEnvs
  - group: "${{ parameters.environmentName }}"
  - template: "/pipelines/vars/common.yaml"
  - template: "/pipelines/vars/${{ lower(parameters.environmentName) }}.yaml"

resources:
  repositories:
    - repository: ipaffs-qa-automation
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-qa-automation
      ref: refs/heads/imta-21213 # Hardcoded against feature branch for now

steps:
  - checkout: self

  - checkout: ipaffs-qa-automation
    path: s/ipaffs-qa-automation

  - task: AzureCLI@2
    displayName: Update QA Automation environment file
    inputs:
      azureSubscription: $(serviceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: $(Pipeline.Workspace)/s/ipaffs-qa-automation
      inlineScript: |
        $(Pipeline.Workspace)/s/ipaffs-infra/scripts/pipeline/substitute-environment-variables.sh .env-kv $(keyVaultName) .env-substituted
  - task: AzureCLI@2
    displayName: Run Container
    inputs:
      azureSubscription: $(serviceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: $(Pipeline.Workspace)/s/ipaffs-qa-automation
      inlineScript: |
        set -x
        az acr login --name "$(acrName)" --subscription "$(subscriptionName)"
        docker pull $(acrLoginServer)/ipaffs/qa-automation:${{ parameters.imageTag }}

        docker run --env-file .env-substituted -v "$PWD:/app" $(acrLoginServer)/ipaffs/qa-automation:${{ parameters.imageTag }}
        # docker run --env-file .env-substituted $(acrLoginServer)/ipaffs/qa-automation:${{ parameters.imageTag }} test -- --grep "@smoke"
