name: Test Bicep

trigger:
- main

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'ADO-DefraGovUK-AZR-IMP-SND1'
    subscriptionId: 'cfa4ccd1-5a5e-420c-9bca-03218a43e46d'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'bicep/test.bicep'
    deploymentMode: 'Incremental'

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
