trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - helm-charts/webapp/

pr:
  branches:
    include:
      - main
  paths:
    include:
      - helm-charts/webapp/

pool:
  name: 'DEFRA-COMMON-ubuntu2204-SSV5'

variables:
  azureSubscription: 'ADO-DefraGovUK-AZR-POC_IMP'
  acrName: 'pocimpinfac1401'
  helmChartPath: './helm-charts/webapp'
  helmChartName: 'webapp'

stages:
  - stage: Package
    jobs:
      - job: ExtractVersionFromChart
        displayName: Extract Chart Version
        steps:
          - script: |
              version=$(yq '.version' Chart.yaml)
              echo "##vso[task.setvariable variable=helmChartVersion;isOutput=true]$version"
            workingDirectory: $(helmChartPath)
            name: ComputeVersion
      - job: PackageFeatureBranch
        displayName: Package feature branch
        condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
        dependsOn: ExtractVersionFromChart
        variables:
          helmChartVersion: $[ dependencies.ExtractVersionFromChart.outputs['ComputeVersion.helmChartVersion'] ]
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo Logging in to ACR
                az acr login --name $(acrName)
                  
                echo Generating Version Label
                VERSION="$(helmChartVersion)+build.$(Build.BuildNumber)"
                echo "Version Label: ${VERSION}"
                
                echo Packaging Helm Chart
                helm package $(helmChartPath) --version ${VERSION}
                
                echo Pushing Helm chart to ACR
                helm push $(helmChartName)-${VERSION}.tgz oci://$(acrName).azurecr.io/helm/v1/repo
      - job: PackageMainBranch
        displayName: Bump chart version and package main branch
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        dependsOn: ExtractVersionFromChart
        variables:
          helmChartVersion: $[ dependencies.ExtractVersionFromChart.outputs['ComputeVersion.helmChartVersion'] ]
          gitUserName: 'IPAFFS CI Bot'
          gitUserEmail: 'ipaffs-ci-bot@defra.gov.uk'
        steps:
          - checkout: self
            persistCredentials: true
            clean: true
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo Bumping Chart Version
                git config user.name "$(gitUserName)"
                git config user.email "$(gitUserEmail)"
                git fetch origin
                git checkout main
                
                CURRENT_VERSION=$(helmChartVersion)
                NEW_VERSION="${CURRENT_VERSION%.*}.$((${CURRENT_VERSION##*.} + 1))"
                yq -i ".version = \"${NEW_VERSION}\"" $(helmChartPath)/Chart.yaml
               
                git add $(helmChartPath)/Chart.yaml
                git diff --cached
                git commit -m "[skip ci] build(deps): Bumping Chart version from $(helmChartVersion) to ${NEW_VERSION}"
                git push
                
                echo Logging in to ACR
                az acr login --name $(acrName)
                
                echo Packaging Helm Chart
                helm package $(helmChartPath) --version ${NEW_VERSION}

                echo Pushing Helm chart to ACR
                helm push $(helmChartName)-${NEW_VERSION}.tgz oci://$(acrName).azurecr.io/helm/v1/repo
