trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - helm-charts/webapp/

pool:
  name: 'DEFRA-COMMON-ubuntu2204-SSV5'

variables:
  azureSubscription: 'ADO-DefraGovUK-AZR-POC_IMP'
  acrName: 'pocimpinfac1401'
  helmChartPath: './helm-charts/webapp'
  helmChartName: 'webapp'

stages:
  - stage: Build
    jobs:
      - job: ExtractVersionFromChart
        steps:
          - script: |
              version=$(yq '.version' Chart.yaml)
              echo "##vso[task.setvariable variable=helmChartVersion;isOutput=true]version"
            workingDirectory: $(helmChartPath)
            name: ComputeVersion
        displayName: Compute version
      - job: BuildFeatureBranchArtifactWebApp
        condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Logging in to ACR."
                az acr login --name $(acrName)
                  
                echo "Generating Version Label"]
                echo $[ dependencies.ExtractVersionFromChart.outputs[ComputeVersion.helmChartVersion] ]
                VERSION="$(helmChartVersion)+build.$(Build.BuildNumber)"
                echo "Version Label: ${VERSION}"
                
                echo "Packaging Helm Chart."
                helm package $(helmChartPath) --version ${VERSION}
                
                echo "Pushing Helm chart to ACR."
                helm push $(helmChartName)-${VERSION}.tgz oci://$(acrName).azurecr.io/helm/v1/repo
      - job: BuildMainBranchArtifactWebApp
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Hello world."
