{{- if .Values.externalSecret.enabled }}
{{- $refreshInterval := required "externalSecret.refreshInterval is required" .Values.externalSecret.refreshInterval }}
{{- $secretStoreName := required "secretStore.name is required" .Values.secretStore.name }}
{{- $certs := .Values.externalSecret.certs | default (list) }}

{{- range $certs }}
{{- $certRemoteKey := required "externalSecret.certs[].remoteKey is required" .remoteKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "externalSecret.certs[].secretKey is required" .secretKey }}
  labels:
    app.kubernetes.io/name: ms-identity-redirect-handler
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $secretStoreName }}
  target:
    name: {{ required "externalSecret.certs[].secretKey is required" .secretKey }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/tls
      data:
        tls.crt: {{ printf "{{ .pkcs12 | b64dec | pkcs12cert }}" | quote }}
        tls.key: {{ printf "{{ .pkcs12 | b64dec | pkcs12key }}" | quote }}
  data:
    - secretKey: pkcs12
      remoteRef:
        {{- if hasPrefix "secret/" $certRemoteKey }}
        key: {{ $certRemoteKey }}
        {{- else if hasPrefix "cert/" $certRemoteKey }}
        key: {{ printf "secret/%s" (trimPrefix "cert/" $certRemoteKey) }}
        {{- else }}
        key: {{ printf "secret/%s" $certRemoteKey }}
        {{- end }}
{{- end }}
{{- end }}

# vim: set ts=2 sts=2 sw=2 et:
