apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-identity-redirect-handler
  labels:
    app.kubernetes.io/name: ms-identity-redirect-handler
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ printf "ipaffs-redirect-%s.azure.defra.cloud" .Values.environment | quote }}
      secretName: ipaffs-tls
  rules:
    - host: {{ printf "ipaffs-redirect-%s.azure.defra.cloud" .Values.environment | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "ms-identity-redirect-handler"
                port:
                  number: 80

# vim: set ts=2 sts=2 sw=2 et:
