apiVersion: v1
kind: Service
metadata:
  name: ms-identity-redirect-handler
  labels:
    app.kubernetes.io/name: ms-identity-redirect-handler
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ms-identity-redirect-handler

# vim: set ts=2 sts=2 sw=2 et:
