---
variables:
  classicServiceConnection: ADO-DefraGovUK-AZR-IMP-SND1
  classicSqlAdminUserPrincipalObjectId: aaf71566-6255-442e-a51d-1633b56a01c2
  classicSubscriptionName: AZR-SND
  commonGroupsServiceConnection: ADO-DefraGovUK-AZR-IMP-DEV1
  dnsResourceGroupName: DEVIMPZONRGP001
  dnsSubscriptionId: 20168d22-67f1-4cd0-bb56-3db91aec16ff # AZR-DEV
  entraAccessGroupBaseName: AAG-Azure-AZR_IMP_DEV1
  serviceConnection: ADO-DefraGovUK-AZR-IMP-DEV1
  serviceConnectionPrincipalId: c5daee65-10cb-4d04-b721-d3da81357568
  subscriptionName: AZR-IMP-DEV1
  sqlServerClassicManagedIdentityObjectId: 4c300f46-508c-4753-a6b5-7f5c007d4012

# vim: set ts=2 sts=2 sw=2 et:
