---
schedules:
  - cron: "0 6 * * 1-5"
    displayName: "Run Validation scripts nightly"
    branches:
      include: [ main ]
    always: true

trigger: none
pr: none

pool:
  name: DEFRA-COMMON-ubuntu2204-SSV5

variables:
  - group: "Common"
  - template: "/pipelines/vars/dev.yamlƒ"

jobs:
  - job: TriggerCorePipeline
    steps:
      - task: AzureCLI@2
        name: TriggerQAPipeline
        displayName: Trigger QA Pipeline
        env:
          PIPELINE_ID: 11803
          ADO_ORG_URL: $(System.CollectionUri)
          ADO_PROJECT: $(System.TeamProject)
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az pipelines run \
              --id ${PIPELINE_ID} \
              --org "${ADO_ORG_URL}" \
              --project "${ADO_PROJECT}" \
              --parameters environmentName="TST"
