{{- $azure := .Values.azure -}}
{{- $authType := default "WorkloadIdentity" $azure.authType -}}
{{- $saName := default "external-secrets" $azure.serviceAccountRef.name -}}
{{- $saNamespace := default .Release.Namespace $azure.serviceAccountRef.namespace -}}
{{- $sp := $azure.servicePrincipal -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "external-secrets-azure.fullname" . }}
spec:
  provider:
    azurekv:
      vaultUrl: {{ required "azure.vaultUrl is required" $azure.vaultUrl | quote }}
      tenantId: {{ required "azure.tenantId is required" $azure.tenantId | quote }}
      authType: {{ $authType | quote }}
      {{- if eq $authType "WorkloadIdentity" }}
      identityId: {{ required "azure.identityId is required when authType is WorkloadIdentity" $azure.identityId | quote }}
      serviceAccountRef:
        name: {{ required "azure.serviceAccountRef.name is required when authType is WorkloadIdentity" $saName | quote }}
        namespace: {{ required "azure.serviceAccountRef.namespace is required when authType is WorkloadIdentity" $saNamespace | quote }}
      {{- else if eq $authType "ManagedIdentity" }}
      identityId: {{ required "azure.identityId is required when authType is ManagedIdentity" $azure.identityId | quote }}
      {{- else if eq $authType "ServicePrincipal" }}
      clientId: {{ required "azure.servicePrincipal.clientId is required when authType is ServicePrincipal" $sp.clientId | quote }}
      clientSecretSecretRef:
        name: {{ required "azure.servicePrincipal.secretName is required when authType is ServicePrincipal" $sp.secretName | quote }}
        key: {{ required "azure.servicePrincipal.clientSecretKey is required when authType is ServicePrincipal" $sp.clientSecretKey | quote }}
        namespace: {{ default .Release.Namespace $sp.secretNamespace | quote }}
      {{- end }}
