apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: defra-certificate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-azure-ccoe
  target:
    name: defra-certificate
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ `{{ .star-azure-defra-cloud-cert | b64dec | pkcs12cert }}` }}"
        tls.key: "{{ `{{ .star-azure-defra-cloud-cert | b64dec | pkcs12key }}` }}"
  data:
    - secretKey: star-azure-defra-cloud-cert
      remoteRef:
        key: secret/star-azure-defra-cloud-cert

# vim: set ts=2 sts=2 sw=2 et:
