{{- $azure := .Values.azure -}}
{{- $authType := default "WorkloadIdentity" $azure.authType -}}
{{- $sp := $azure.servicePrincipal -}}
{{- if and (eq $authType "ServicePrincipal") $sp.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "azure.servicePrincipal.secretName is required when creating a service principal secret" $sp.secretName | quote }}
  namespace: {{ default .Release.Namespace $sp.secretNamespace | quote }}
type: Opaque
stringData:
  {{ required "azure.servicePrincipal.clientIdKey is required when creating a service principal secret" $sp.clientIdKey }}: {{ required "azure.servicePrincipal.clientId is required when creating a service principal secret" $sp.clientId | quote }}
  {{ required "azure.servicePrincipal.clientSecretKey is required when creating a service principal secret" $sp.clientSecretKey }}: {{ required "azure.servicePrincipal.clientSecret is required when creating a service principal secret" $sp.clientSecret | quote }}
{{- end }}
