apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: {{ template "ipaffs-common.azure.resourceGroup" . }}
  labels:
    {{- include "ipaffs-common.labels" . | nindent 4 }}
spec:
  location: {{ .Values.azure.location }}

# vim: set ts=2 sts=2 sw=2 et:
