{{ if .Values.database.enabled }}
{{ range $databaseName := .Values.database.databaseNames }}
{{ $db := dict "databaseName" $databaseName "Values" $.Values "Release" $.Release }}
---
apiVersion: sql.azure.com/v1api20211101
kind: ServersDatabase
metadata:
  name: {{ template "ipaffs-common.azure.databaseName" $db }}
  labels:
    {{- include "ipaffs-common.labels" $db | nindent 4 }}
  annotations:
    serviceoperator.azure.com/reconcile-policy: manage
spec:
  owner:
    name: {{ template "ipaffs-common.azure.sqlServer" $db }}
  collation: SQL_Latin1_General_CP1_CI_AS
  location: {{ .Values.azure.location }}

{{ end }}
{{ end }}

# vim: set ts=2 sts=2 sw=2 et:
