{{ if .Values.database.enabled }}

apiVersion: sql.azure.com/v1api20211101
kind: Server
metadata:
  name: {{ template "deploy.azure.sqlServer" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  owner:
    name: {{ template "deploy.azure.resourceGroup" . }}
  location: {{ .Values.azure.location }}

---
apiVersion: sql.azure.com/v1api20211101
kind: ServersDatabase
metadata:
  name: {{ template "deploy.azure.databaseName" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
  annotations:
    serviceoperator.azure.com/reconcile-policy: manage
spec:
  owner:
    name: {{ template "deploy.azure.sqlServer" . }}
  collation: SQL_Latin1_General_CP1_CI_AS
  location: {{ .Values.azure.location }}

{{ end }}

# vim: set ts=2 sts=2 sw=2 et:
