{{- if .Values.externalSecret.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-secrets" .Values.service }}
  labels:
    {{- include "ipaffs-common.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ required "externalSecret.refreshInterval is required" .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ required "secretStore.name is required" .Values.secretStore.name }}
  target:
    name: {{ required "externalSecret.name is required" .Values.externalSecret.name }}
    creationPolicy: Owner
  data:
{{- $secrets := required "externalSecret.secrets is required" .Values.externalSecret.secrets }}
{{- range $secrets }}
    - secretKey: {{ required "externalSecret.secrets[].secretKey is required" .secretKey }}
      remoteRef:
        key: {{ required "externalSecret.secrets[].remoteKey is required" .remoteKey }}
{{- end }}

{{- end }}

# vim: set ts=2 sts=2 sw=2 et:
