apiVersion: managedidentity.azure.com/v1api20230131
kind: UserAssignedIdentity
metadata:
  name: {{ template "ipaffs-common.azure.managedIdentityBaseName" . }}-service
  labels:
    {{- include "ipaffs-common.labels" . | nindent 4 }}
  annotations:
    serviceoperator.azure.com/reconcile-policy: manage
spec:
  location: uksouth
  owner:
    name: {{ template "ipaffs-common.azure.resourceGroup" . }}

# vim: set ts=2 sts=2 sw=2 et:
