{
 "title": "IPAFFS_AKS_Stack",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Environment", "query": "prometheus" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": {}
   },
   { "name": "resourceGroup", "label": "Resource Group" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": {}
   },
   {
    "name": "subscription_id",
    "label": "subscription_id",
    "query": {
     "query": "label_values(kube_pod_info, microsoft.subscriptionid)"
    }
   },
   {
    "name": "environment",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployed Services",
   "type": "table",
   "description": "Deployed Services with versions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_labels{namespace=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Imports Proxy Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "requests\n| where $__timeFilter(timestamp)\n| where cloud_RoleName == 'imports-proxy'\n| where resultCode != '0'\n| where url !contains '/admin/health-check'\n// calculate average request duration for all requests\n| summarize Code = count() by strcat(substring(resultCode, 0, 1), 'xx'), bin(timestamp, $__interval * 3)\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "exceptions\n| where $__timeFilter(timestamp)\n| where type !contains 'NotificationConcurrentModificationException'\n// calculate average request duration for all requests\n| summarize exceptions = count() by bin(timestamp, $__interval)\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "HTTP Request Duration by Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "requests\n| where $__timeFilter(timestamp)\n| where resultCode != 0\n| where url !contains '/admin/health-check'\n| summarize (p50, p75, p90, p95, p99) = percentiles(duration, 50, 75, 90, 95, 99) by bin(timestamp, $__interval)\n",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "time_series"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "requests\n| project baseline = 3000\n",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Risk Engine Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "dependencies\r\n| where $__timeFilter(timestamp)\r\n| where cloud_RoleName contains \"risk-assessment\"\r\n| where name contains \"trade-risk-assessment\"\r\n| summarize Code = count() by strcat(substring(resultCode, 0, 1), 'xx'), bin(timestamp, $__interval * 3)\r\n| order by timestamp asc ",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "time_series"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "dependencies\r\n| where $__timeFilter(timestamp)\r\n| where cloud_RoleName contains \"frontend\"\r\n| where target contains \"risk-assessment\"\r\n| where duration >23000\r\n| summarize Timeouts = count() by bin(timestamp, $__interval * 3)\r\n| order by timestamp asc ",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "SoapSearch OpCode Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "exceptions\n| where $__timeFilter(timestamp)\n| where cloud_RoleName contains \"soapsearch\"\n| where tostring(details[0].message) contains \"_\"\n| where tostring(details[0].message) !contains \" \"\n| summarize OpCode = count() by tostring(details[0].message), bin(timestamp, $__interval * 30)\n| order by timestamp asc\n\n\n",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Database Pool DTU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/elasticpools",
      "dimensionFilters": [],
      "metricName": "eDTU_used",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/elasticpools",
        "resourceGroup": "SNDIMPINFRGP001",
        "resourceName": "sndimpdbssqa001/sndimpdbssqa001",
        "subscription": "AZR-SND"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/elasticpools",
      "dimensionFilters": [],
      "metricName": "eDTU_limit",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/elasticpools",
        "resourceGroup": "SNDIMPINFRGP001",
        "resourceName": "sndimpdbssqa001/sndimpdbssqa001",
        "subscription": "AZR-SND"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/elasticpools",
      "dimensionFilters": [],
      "metricName": "eDTU_used",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "resourceGroup": "$resourceGroup",
        "resourceName": "tstimpdbssqa001/tstimpedpsqa001",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/elasticpools",
      "dimensionFilters": [],
      "metricName": "eDTU_limit",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "resourceGroup": "$resourceGroup",
        "resourceName": "tstimpdbssqa001/tstimpedpsqa001",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/elasticpools",
      "dimensionFilters": [],
      "metricName": "eDTU_used",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "resourceGroup": "$resourceGroup",
        "resourceName": "preimpdbssqa001/preimpedpsqa001",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/elasticpools",
      "dimensionFilters": [],
      "metricName": "eDTU_limit",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "resourceGroup": "$resourceGroup",
        "resourceName": "preimpdbssqa001/preimpedpsqa001",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Re-sent Notifications (CHEDPP re-sync)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "mode": "raw",
      "query": "traces\r\n| where $__timeFilter(timestamp)\r\n| where message contains \"Notification resent\"\r\n| project timestamp, referenceNumber = extract('referenceNumber=(.*), status', 1, message), status = extract('status=(.*), commodityCodes', 1, message), commodityCodes = extract('commodityCodes=(.*), country', 1, message), countryOfOrigin = extract('countryOfOrigin=(.*), last', 1, message), lastUpdated = extract('lastUpdated=(.*), synced', 1, message), syncedAt = extract('syncedAt=(.*), triggered', 1, message), triggeredBy = extract('triggeredBy=(.*)', 1, message)\r\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Soap Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "requests\r\n| where $__timeFilter(timestamp)\r\n| where cloud_RoleName contains 'soapsearch'\r\n| where url !contains 'wsdl'\r\n| summarize requests = count() by bin(timestamp, $__interval * 5)\r\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$resource"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}