apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploy.fullname" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  replicas: {{ index .Values.environments .Values.environment "replicaCount" | default 1 }}
  selector:
    matchLabels:
      {{- include "deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deploy.labels" . | nindent 8 }}
    spec:
      serviceAccountName: ipaffs
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ include "deploy.name" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "deploy.fullname" . }}
            - secretRef:
                name: {{ include "deploy.fullname" . }}
